<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<link rel="stylesheet" type="text/css" href="/css/device_create.css?rand=<?php echo rand(); ?>">
<script type='text/javascript' src='/js/jquery-1.11.3.min.js'></script>
<script type='text/javascript' src='/js/jquery.form.js'></script>
<script type='text/javascript' src='/js/jquery.validate.js'></script>
<script type='text/javascript' src='/js/jquery.blockUI.js'></script>
<ul id='title'>
	<li><a href='/'>首頁</a></li>
	<li> > </li>
	<li style='color:#86c557;'>新 增 註 册 Tag</li>
</ul>
		<div>
			<form action="/device/create" id='create_form' method="post" enctype="multipart/form-data">
			<div id="addSerial">
				<div class="green_text title">步 驟 一 : 請輸入產品序號</div>
				<!-- need to check serial number and highlight tag kind
				<div class="blue_text title" style='margin-top:6%;margin-bottom:2%;'>產品類別:</div>
				
				<table id='tagKind_table'>
					<tr>
						<td  class="tagKind_container green_text">
							<img id='qrcode' src="/img/13/icon-01-02.png"><br/>Q tag
						</td>
						<td class="tagKind_container green_text">
							<img id='nfc'  src="/img/13/icon-02-02.png"><br/>N tag
						</td>
						<td class="tagKind_container green_text">
							<img id='ble'  src="/img/13/icon-03-02.png"><br/>B tag
						</td>
					</tr>
				</table>
				
				<div class='clear'></div>
				 -->
				<span class="blue_text">產品序號</span><br>
				<input id="sn" type="text" name="serial_number" style='text-align:center;height:2em;' value="<?php if(!empty($_GET["sn"])) echo $_GET["sn"] ?>" placeholder="輸 入 你 的 商 品 序 號 / UID" class="textfield" required><br>
				<a id="help_button" href='' ><img src='/img/13/icon-04.png'/></a>
				<button type="submit" id="addSerial_next" class="button" style="height:3em;background:#EB004E;margin-bottom:2em;">完 成</button>
				<!-- <button id="addSerial_next" type='button' class="orange_button" style="height:3em;">下 一 步 ></button>  -->
			</div>
			<div class="clear"></div>
			</form>
			
			
			
		</div>
	
		<script>
			var device_type = '<?php echo $device_type; ?>';
			var get_sn = "<?php if(!empty($_GET["sn"])) echo $_GET["sn"]; ?>";
		</script>
		
		<script type='text/javascript' src='/js/device_create.js'></script>
	</body>
</html>