<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<link rel="stylesheet" type="text/css" href="/css/index.css?rand=<?php echo rand(); 	?>">
<link rel="stylesheet" type="text/css" href="/css/device_index.css?rand=<?php echo rand(); 	?>">
<script type='text/javascript' src='/js/jquery-1.11.3.min.js'></script>
<script type='text/javascript' src='/js/device_index.js'></script>
<div id='device_img_wrapper'>
	<?php 
	if(empty($device->photo)) {
		if(!empty($device->type)) {
			switch($device->type) {
				case "Pets":
					echo '<img src="/img/17/pic-02.png">';
					break;
				case "Human":
					echo '<img src="/img/17/pic-01.png">';
					break;
				case "Valuables":
					echo '<img src="/img/17/pic-03.png">';
				default:
					break;
			}
		}
	}
	else {
		echo "<img src='{$device->photo}'/>";
	}
	?>
	<div></div>
	<h3><?php echo $device->name?> </h3>
</div>
<div id="tab_container">
	<ul>
		<li id="petInfo_tab" class='pet_tab pet_notication_tab'><span>遺 失 資 料</span></li>
		<li id="petHealth_tab" class='pet_tab pet_info_tab' ><span>基 本 資 料</span></li>
		<!-- 
		<li class='tab notication_tab'><img id="notice_background" src="/img/02/bu-01-01.png" style="margin-top:3%;"/><span>通 知 事 項</span></li>
		<li class='tab info_tab' ><img id="info_background" src="/img/02/bu-02-01.png"/><span>基 本 資 料</span></li>
		 -->
	</ul>
</div>

<div id="notice_container">
	<div class="green_text title">
		<img src="/img/02/icon-01.png" />遺 失 資 料
	</div>
	<div class="black_text"><?php if($device->status == 'lost') echo $device->lost_message; ?></div>
	<table id="notice_table">
		<tr>
			<th class="blue_text">走失時間:</th>
			<td class="black_text"><?php if($device->status == 'lost') { if(!empty($device->lost_date)) echo date('Y/m/d',strtotime($device->lost_date)); else echo "目前沒有內容";} ?>
				<?php
					
				?>
			</td>
		</tr>
		<tr>
			<th class="blue_text">走失地點:</th>
			<td class="black_text"><?php if($device->status == 'lost') { if(!empty($device->lost_location)) echo $device->lost_location; else echo "目前沒有內容";} ?>
				<?php
					
				?>
			</td>
		</tr>
		<tr>
			<th class="blue_text">穿著(特徵):</th>
			<td class="black_text"><?php if($device->status == 'lost') { if(!empty($device->lost_spec)) echo $device->lost_spec; else echo "目前沒有內容";} ?>
				<?php
					
				?>
			</td>
		</tr>
		<?php 
		if($device->status == 'lost') {
			if(!empty($lost_contacts)) {
				foreach($lost_contacts as $r) {
					if($r->id == $device->lost_contact_id) {
						echo <<<EOT
<tr>
	<th class="blue_text">聯絡方式:</th>
	<td class="orange_text" style="width:30%">
	{$r->name}
	</td>
	<td class="orange_text" style="width:30%">
	{$r->phone}
	</td>
</tr>					
EOT;
					}
					if($r->id == $device->lost_contact_id_2) {
						echo <<<EOT
<tr>
	<th class="blue_text">聯絡方式:</th>
	<td class="orange_text" style="width:30%">
	{$r->name}
	</td>
	<td class="orange_text" style="width:30%">
	{$r->phone}
	</td>
</tr>
EOT;
					}
					if($r->id == $device->lost_contact_id_3) {
						echo <<<EOT
<tr>
	<th class="blue_text">聯絡方式:</th>
	<td class="orange_text" style="width:30%">
	{$r->name}
	</td>
	<td class="orange_text" style="width:30%">
	{$r->phone}
	</td>
</tr>
EOT;
					}
				}
			}
		}
		
		?>
	</table>				
	
	<div id='add_notication_div'>
		<a  href="/guestbook/create?serial_number=<?php echo $device->serial_number; ?>">
		通 知 / 留 言
		</a>
		</a>
	</div>
		
</div>

<div id="info_container">
	<div id="info_container_wrapper">
		<div class="green_text title">
			<img src="/img/02/icon-01.png" />基本資料
		</div>
		<table id="info_table">
			<?php if($device->type == 'Pets') { ?>
			<tr>
				<th class="blue_text">種類:</th>
				<td class="black_text">
					<?php
						switch(strtolower($device->category)){
							case 'dogs':
								echo "狗類";
								break;
							case 'cats':
								echo "貓類";
								break;
							default:
								echo "";
								break;
						}
					?>
				</td>
			</tr>
			<tr>
				<th class="blue_text">年齡:</th>
				<td class="black_text">
					<?php
						if(!empty($info->birthday)) {
						
							//Calculate age
							$birthDate = $info->birthday;
							//explode the date to get month, day and year
							$birthDate = explode("-", $birthDate);
			
							//get age from date or birthdate
							$age = (date("md", date("U", mktime(0, 0, 0, $birthDate[0], $birthDate[1], $birthDate[2]))) > date("md")
									? ((date("Y") - $birthDate[0]) - 1)
									: (date("Y") - $birthDate[0]));
							echo $age . " 歲";
						}
					?>
				</td>
			</tr>
			<tr>
				<th class="blue_text">性別:</th>
				<td class="black_text">
					<?php
						if(!empty($info->sex)) {
						
							switch($info->sex) {
								case "m":
									echo "公";
									break;
								case "f":
									echo "母";
									break;
								default:
									break;
							}
						}
					?>
				</td>
			</tr>
			<tr>
				<th class="blue_text">晶片植入:</th>
				<td class="black_text">
				<?php
					echo !empty($info->chip_number) ? "有" : "無";
				?>
				</td>
			</tr>
			<tr>
				<th class="blue_text">生日:</th>
				<td class="black_text">
					<?php echo $info->birthday; ?>
				</td>
			</tr>
			<tr>
				<th class="blue_text">身長:</th>
				<td class="black_text">
					<?php echo $info->height . " cm"; ?>
				</td>
			</tr>
			<tr>
				<th class="blue_text">體重:</th>
				<td class="black_text">
					<?php echo $info->weight . " kg"; ?>
				</td>
			</tr>
			<tr>
				<th class="blue_text">個性:</th>
				<td class="black_text">
					<?php echo $info->temperament; ?>
				</td>
			</tr>
			<tr>
				<th class="blue_text">特殊才能:</th>
				<td class="black_text">
					<?php echo $info->talents; ?>
				</td>
			</tr>
			<tr>
				<th class="blue_text">簡介:</th>
				<td class="black_text">
					<?php echo $info->description; ?>
				</td>
			</tr>
				<?php if($device->open == 'y') {?>
					<tr>
						<th class="blue_text">晶片號碼:</th>
						<td class="black_text">
							<?php echo $info->chip_number; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">結紮:</th>
						<td class="black_text">
							<?php
								if(!empty($info->desex)) {
								
									switch($info->desex) {
										case "y":
											echo "有";
											break;
										case "n":
											echo "無";
											break;
										default:
											break;
									}
								}
							?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">預防針種類:</th>
						<td class="black_text">
							<?php echo $info->vaccine_type; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">血型:</th>
						<td class="black_text">
							<?php echo $info->bloodtype . " 型"; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">血庫資訊通知:</th>
						<td class="black_text">
							<?php
								if(!empty($info->bloodbank)) {
								
									switch($info->bloodbank) {
										case "y":
											echo "有";
											break;
										case "n":
											echo "無";
											break;
										default:
											break;
									}
								}
							?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">肢體障礙:</th>
						<td class="black_text">
							<?php echo $info->disability; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">保險單號:</th>
						<td class="black_text">
							<?php echo $info->insurance; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">醫院名稱:</th>
						<td class="black_text">
							<?php echo $info->hospital_name; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">醫院電話:</th>
						<td class="black_text">
							<?php echo $info->hospital_phone; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">醫院地址:</th>
						<td class="black_text">
							<?php echo $info->hospital_address; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">城市:</th>
						<td class="black_text">
							<?php echo $info->hospital_city; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">鄉鎮市區:</th>
						<td class="black_text">
							<?php echo $info->hospital_district; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">郵遞區號:</th>
						<td class="black_text">
							<?php echo $info->hospital_postal; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">國別:</th>
						<td class="black_text">
							<?php echo $info->hospital_country; ?>
						</td>
					</tr>
				<?php } ?>
				
			<?php } ?>
			
			<?php if($device->type == 'Human') { ?>
			<tr>
				<th class="blue_text">性別:</th>
				<td class="black_text">
				<?php
					if(!empty($info->sex)) {
					
						switch($info->sex) {
							case "m":
								echo "男";
								break;
							case "f":
								echo "女";
								break;
							default:
								break;
						}
					}
				?>
				</td>
			</tr>
			<tr>
				<th class="blue_text">年齡:</th>
				<td class="black_text">
					<?php
						if(!empty($info->birthday)) {
						
							//Calculate age
							$birthDate = $info->birthday;
							//explode the date to get month, day and year
							$birthDate = explode("-", $birthDate);
			
							//get age from date or birthdate
							$age = (date("md", date("U", mktime(0, 0, 0, $birthDate[0], $birthDate[1], $birthDate[2]))) > date("md")
									? ((date("Y") - $birthDate[0]) - 1)
									: (date("Y") - $birthDate[0]));
							echo $age . " 歲";
						}
					?>
				</td>
			</tr>
				<?php if($device->open == 'y') {?>
					<tr>
						<th class="blue_text">高度:</th>
						<td class="black_text">
							<?php echo $info->height . " cm"; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">體重:</th>
						<td class="black_text">
							<?php echo $info->weight . " kg"; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">血型:</th>
						<td class="black_text">
							<?php echo strtoupper($info->bloodtype) . " 型"; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">疾病:</th>
						<td class="black_text">
							<?php echo $info->disease; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">肢體障礙:</th>
						<td class="black_text">
							<?php echo $info->disability; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">服用藥物:</th>
						<td class="black_text">
							<?php echo $info->medications; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">醫院名稱:</th>
						<td class="black_text">
							<?php echo $info->hospital_name; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">醫院電話:</th>
						<td class="black_text">
							<?php echo $info->hospital_phone; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">醫院地址:</th>
						<td class="black_text">
							<?php echo $info->hospital_address; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">城市:</th>
						<td class="black_text">
							<?php echo $info->hospital_city; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">鄉鎮市區:</th>
						<td class="black_text">
							<?php echo $info->hospital_district; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">郵遞區號:</th>
						<td class="black_text">
							<?php echo $info->hospital_postal; ?>
						</td>
					</tr>
					<tr>
						<th class="blue_text">國別:</th>
						<td class="black_text">
							<?php echo $info->hospital_country; ?>
						</td>
					</tr>
				<?php } ?>
			<?php } ?>
			
			<?php if($device->type == 'Valuables') { ?>
				<tr>
					<th class="blue_text">名稱:</th>
					<td class="black_text">
						<?php echo $info->name; ?>
					</td>
				</tr>
				<tr>
					<th class="blue_text">特徵/敘述:</th>
					<td class="black_text">
						<?php echo $info->description; ?>
					</td>
				</tr>
			<?php } ?>
		</table>
	</div>	
	<?php 
	if(!empty($photos)) {
		foreach($photos as $r) {
			echo "<img class='photo' src='{$r->photo}'/>";
		}
	}
	?>
	<div style='clear:both'></div>
</div>

<script>
	var status = '<?php echo $device->status;?>'
</script>
