<link rel="stylesheet" type="text/css" href="/css/device_update_index.css?rand=<?php echo rand(); ?>">
<script type='text/javascript' src='/js/jquery-1.11.3.min.js'></script>
<script type='text/javascript' src='/js/jquery.form.js'></script>
<script type='text/javascript' src='/js/jquery.validate.js'></script>
<script type='text/javascript' src='/js/jquery.blockUI.js'></script>
<script type='text/javascript' src='/js/device_update_index.js?rand=<?php echo rand(); ?>'></script>
<ul id='title'>
	<li><a href='/'>首頁</a></li>
	<li> > </li>
	<li><a href='/device/index?serial_number=<?php echo $device->serial_number; ?>'>管理名單</a></li>
	<li> > </li>
	<li style='color:#86c557;'><?php echo $device->name; ?></li>
</ul>
<div id='device_menu_container'>
	<div class="blue_text title">照片</div>
	<input type='hidden' name='serial_number' value='<?php echo $device->serial_number; ?>'/>
	<div>
		<form id='update_photo_form' method='post' action='/device/updatePhoto' style='display:none;'>
			<input type='file' name="photos" class="photos" style='width:0;height:0;'/>
			<input type='hidden' name='serial_number' value='<?php echo $device->serial_number; ?>'/>
		</form>
		<div id='img_wrapper'>
			<div style='margin:0 auto;position:relative;'>
				<img id="pic" src= "/<?php echo $device->photo?>"/>
				<img id='upload_btn' src="/img/08/frame.png" />
			</div>
		</div>
		<div id='info_wrapper'>
			<div><?php echo $device->name ?></div>
			<div>
				<?php
					//determine 'kind' from serial number
					$kind = '';
					
					if(!empty($device->serial_number))
						$kind = $device->serial_number[2];
					
					switch($kind){
						case "Q":
							$kind = "Q-tag";
							break;
						case "B":
							$kind = "B-tag";
							break;
						case "N":
							$kind = "N-tag";
							break;
						default:
							break;
					}
					
					echo $kind;
				?>
			</div>
			<div>USID: <?php echo $device->serial_number ?></div>
		</div>
		<div class="clear"></div>
	</div>
	
	<div class="blue_text" style='margin:5% 0 5% 0; float:left;'>用途分類</div>
	<div class="green_text" style='margin:5% 0 5% 7%; float:left;'>
		<?php
			//determine 'type' from serial number
			$type = '';
			
			if(!empty($device->serial_number))
				$type = $device->serial_number[0];
			
			switch($type){
				case "P":
					$type = "竉物";
					break;
				case "M":
					$type = "人";
					break;
				case "T":
					$type = "物品";
					break;
				default:
					break;
			}
			
			echo $type;
		?>
	</div>
	<div class="clear"></div>
	<div>
		<font style="color:red;font-size:3.333em;">*</font><span class="blue_text" style='margin-right:3%;'>資料公開</span>
		<input type="radio" name="open" value="y" <?php if($device->open == 'y') echo 'checked';?>><span class='radio_text'>公開</span>
		<input type="radio" name="open" value="n" <?php if($device->open != 'y') echo 'checked';?>><span class='radio_text'>關閉</span>
	</div>
	<br>
	<div>
		<font style="color:red;font-size:3.333em;">*</font><span class="blue_text" style='margin-right:3%;'>遺失狀態</span>
		<input type="radio" name="status" value="lost" <?php if($device->status == 'lost') echo 'checked';?>><span class='radio_text'>遺失</span>
		<input type="radio" name="status" value="normal" <?php if($device->status != 'lost') echo 'checked';?>><span class='radio_text' >關閉</span>
	</div>
</div>

<div>
	<a class='menu' href="/guestbook/list?serial_number=<?php echo $device->serial_number?>">
		<img src="/img/08/bu-01.png" style="width:100%;">
			<?php if($notification_count > 0 ) { ?>
			<span id='notification_count'><?php echo $notification_count; ?></span>
			<?php } ?>
			<span style="position:absolute;bottom:20px;right:10%" class="white_text">訊息通知</span>
	</a>
	<a class='menu'  href="/device/updateInfo?serial_number=<?php echo $device->serial_number?>">
		<img src="/img/08/bu-02.png" style="width:100%;">
		<div style="position:absolute;bottom:20px;right:10%" class="white_text">基本資料</div>
	</a>
	<div class="clear"></div>
</div>

<div>
	<a class='menu'  href="/photo/list?serial_number=<?php echo $device->serial_number?>">
		<img src="/img/08/bu-03.png" style="width:100%;">
		<div style="position:absolute;bottom:20px;right:10%" class="white_text">相片集</div>
	</a>
	<a class='menu'  href="/device/updateStatus?serial_number=<?php echo $device->serial_number?>">
		<img src="/img/08/bu-04.png" style="width:100%;">
		<div style="position:absolute;bottom:20px;right:10%" class="white_text">遺失設定</div>
	</a>
	<div class="clear"></div>
</div>
