<!DOCTYPE html>
<html>
	<head>
<link rel="stylesheet" type="text/css" href="/css/index.css?rand=<?php echo rand(); ?>">
<link rel="stylesheet" type="text/css" href="/css/device_update_info.css?rand=<?php echo rand(); ?>">
<script type='text/javascript' src='/js/jquery-1.11.3.min.js'></script>
<script type='text/javascript' src='/js/jquery.form.js'></script>
<script type='text/javascript' src='/js/jquery.validate.js'></script>
<script type='text/javascript' src='/js/jquery.blockUI.js'></script>
<script type='text/javascript' src='/js/device_update_info.js?rand=<?php echo rand(); ?>'></script>
	</head>
	
	<body>
<ul id='title'>
	<li><a href='/'>首頁</a></li>
	<li> > </li>
	<li><a href='/device/index?serial_number=<?php echo $device->serial_number?>'>管理名單</a></li>
	<li> > </li>
	<li><a href='/device/update?serial_number=<?php echo $device->serial_number?>'><?php echo $device->name?></a></li>
	<li> > </li>
	<li style='color:red;'>基本資料</li>
</ul>

<div>
	<form action="/device/updatePet" method="post">
		
		<input type='hidden' name='serial_number1' value='<?php echo $device->serial_number; ?>'/>
		
		<div id="updatePet">					
			<div id="pet_tab_container">
				<ul>
					<li id="petInfo_tab" class='pet_tab pet_notication_tab'><span>竉物資料</span></li>
					<li id="petHealth_tab" class='pet_tab pet_info_tab' ><span>健康狀況</span></li>
				</ul>
			</div>
			
			<div id="petInfo_container" class='container'>
				<div class='input_div'>
					<div class="blue_text"><font color="red">*</font>竉物名字</div>
	        		<input type="text" name="pet_name" value="<?php if(isset($pet_info)) echo $pet_info->name; ?>" class="textfield" required/>
				</div>
				<div class='input_div'>
					<div class="blue_text">類別</div>
					<input type="text" name="pet_category" value="<?php echo $device->category; ?>" class="textfield"/>
				</div>
				<div class='input_div'>
					<div class="blue_text">性別 
					<input type="radio" name="pet_sex" value="m" style='margin-left:5%;'>公
					<input type="radio" name="pet_sex" value="f" style='margin-left:20%;'>母
					</div>
				</div>
				<div class='input_div'>
					<div class="blue_text">生日</div>
	        		<input name="pet_birthday" value="<?php if(isset($pet_info)) echo $pet_info->birthday; ?>" class="textfield" type='date'/>
				</div>
				<div class='input_div'>
					<div class="blue_text">身高/身長(cm)</div>
	        		<input type="number" name="pet_height" value="<?php if(isset($pet_info)) echo $pet_info->height; ?>" class="textfield"/>
				</div>
				<div class='input_div'>
					<div class="blue_text">體重(kg)</div>
	        		<input type="number" name="pet_weight" value="<?php if(isset($pet_info)) echo $pet_info->weight; ?>" class="textfield"/>
				</div>
				<div class='input_div'>
	        		<table class='checkbox_table'>
	        			<tr>
	        				<th rowspan=4 style='vertical-align: top;'><div class="blue_text">個性</div></th>
	        			</tr>
	        			<tr>
	        				<td><input type="checkbox" name="pet_temperament[]" value="活潑" <?php if(strpos($pet_info->temperament,'活潑') !== false) echo 'checked="checked"'; ?>>活潑</td>
	        				<td><input type="checkbox" name="pet_temperament[]" value="怕生" <?php if(strpos($pet_info->temperament,'怕生') !== false) echo 'checked="checked"'; ?>>怕生</td>
	        			</tr>
	        			<tr>	
	        				<td><input type="checkbox" name="pet_temperament[]" value="容易攻擊" <?php if(strpos($pet_info->temperament,'容易攻擊') !== false) echo 'checked="checked"'; ?>>容易攻擊</td>
	        				<td><input type="checkbox" name="pet_temperament[]" value="具攻擊性" <?php if(strpos($pet_info->temperament,'具攻擊性') !== false) echo 'checked="checked"'; ?>>具攻擊性</td>
	        			</tr>
	        			<tr>
	        				<td colspan=2>
	        					<div style='float:left;'><input type="checkbox" name="pet_temperament[]" value="其他">其他</div>
	        					<input type="text" name="pet_temperament[]" value="" class='textfield' style='float:left;width:50%;font-size:0.5em;margin-left:5%;'/>
	        				</td>
	        			</tr>
	        		</table>
				</div>
				<div class='input_div'>
	        		<table class='checkbox_table'>
	        			<tr>
	        				<th rowspan=4 style='vertical-align: top;'><div class="blue_text">特殊才能</div></th>
	        			</tr>
	        			<tr>
	        				<td><input type="checkbox" name="pet_talents[]" value="坐下" <?php if(strpos($pet_info->talents,'坐下') !== false) echo 'checked="checked"'; ?>>坐下</td>
	        				<td><input type="checkbox" name="pet_talents[]" value="握手" <?php if(strpos($pet_info->talents,'握手') !== false) echo 'checked="checked"'; ?>>握手</td>
	        			</tr>
	        			<tr>	
	        				<td><input type="checkbox" name="pet_talents[]" value="聽名字" <?php if(strpos($pet_info->talents,'聽名字') !== false) echo 'checked="checked"'; ?>>聽名字</td>
	        				<td><input type="checkbox" name="pet_talents[]" value="站立" <?php if(strpos($pet_info->talents,'站立') !== false) echo 'checked="checked"'; ?>>站立</td>
	        			</tr>
	        			<tr>
	        				<td colspan=2>
	        					<div style='float:left;'><input type="checkbox" name="pet_talents[]" value="其他">其他</div>
	        					<input type="text" name="pet_talents[]" value="" class='textfield' style='float:left;width:50%;font-size:0.5em;margin-left:5%;'/>
	        				</td>
	        			</tr>
	        		</table>
				</div>
				<div class='input_div'>
					<div class="blue_text">簡介</div>
	        		<textarea type="text" class='textfield' rows=4 name="pet_description" value="<?php if(isset($pet_info)) echo $pet_info->description; ?>" placeholder="關於竉物的大小事..."></textarea>
				</div>
			</div>
		
			<div id="healthStatus_container" class='container'>
				<div class='input_div'>
					<div class="blue_text"><font color="red">*</font>晶片號碼</div>
	        		<input type="text" name="pet_chip_number" value="<?php if(isset($pet_info)) echo $pet_info->chip_number; ?>" class="textfield" required/>
				</div>
				<div class='input_div'>
					<div class="blue_text">結紮
					<input type="radio" name="pet_desex" value="<?php if(strtolower($pet_info->desex) == 'y') echo 'checked="checked"'; ?>">有
					<input type="radio" name="pet_desex" value="<?php if(strtolower($pet_info->desex) == 'n') echo 'checked="checked"'; ?>" checked>無</div>
				</div>
				<div class='input_div'>
					<div class="blue_text">預防針種類</div>
	        		<input type="text" name="pet_vaccine_type" value="<?php if(isset($pet_info)) echo $pet_info->vaccine_type; ?>" class="textfield"/>
				</div>
				<div class='input_div'>
					<div class="blue_text">血型</div>
	        		<input type="text" name="pet_bloodtype" value="<?php if(isset($pet_info)) echo $pet_info->bloodtype; ?>" class="textfield"/>
				</div>
				<div class='input_div'>
					<div class="blue_text">血庫資訊通知
					<input type="radio" name="pet_bloodbank" value="<?php if(strtolower($pet_info->bloodbank) == 'y') echo 'checked="checked"'; ?>">有
					<input type="radio" name="pet_bloodbank" value="<?php if(strtolower($pet_info->bloodbank) == 'n') echo 'checked="checked"'; ?>">無</div>
				</div>
				<div class='input_div'>
				
	        		<table class='checkbox_table'>
	        			<tr>
	        				<th rowspan=4 style='vertical-align: top;'><div class="blue_text">肢體障礙</div></th>
	        			</tr>
	        			<tr>
	        				<td><input type="checkbox" name="pet_disability[]" value="行動" <?php if(strpos($pet_info->disability,'行動') !== false) echo 'checked="checked"'; ?>>行動</td>
	        				<td><input type="checkbox" name="pet_disability[]" value="聽覺" <?php if(strpos($pet_info->disability,'聽覺') !== false) echo 'checked="checked"'; ?>>聽覺</td>
	        			</tr>
	        			<tr>	
	        				<td><input type="checkbox" name="pet_disability[]" value="視覺" <?php if(strpos($pet_info->disability,'視覺') !== false) echo 'checked="checked"'; ?>>視覺</td>
	        				<td><input type="checkbox" name="pet_disability[]" value="" ></td>
	        			</tr>
	        			<tr>
	        				<td colspan=2>
	        					<div style='float:left;'><input type="checkbox" name="pet_disability[]" value="其他">其他</div>
	        					<input type="text" name="pet_disability[]" value="" class='textfield' style='float:left;width:50%;font-size:0.5em;margin-left:5%;'/>
	        				</td>
	        			</tr>
	        		</table>
	        		
	        		<div class='clear'></div>
				</div>
				<div class='input_div'>
					<div class="blue_text">保險</div>
	        		<input type="text" name="pet_insurance" value="<?php if(isset($pet_info)) echo $pet_info->insurance; ?>" class="textfield" placeholder="填入保險單號"/><br>
				</div>
				<div class='input_div'>
					<div class="blue_text">專屬醫院</div>
	        		<input type="text" name="pet_hospital_name" value="<?php if(isset($pet_info)) echo $pet_info->hospital_name; ?>" class="textfield" placeholder="醫院名稱"/><br>
	        		<input type="number" name="pet_hospital_phone" value="<?php if(isset($pet_info)) echo $pet_info->hospital_phone; ?>" class="textfield" placeholder="醫院電話"/><br>
				</div>
				<div class='input_div'>
	        		<div class="blue_text">醫院地址</div>
	        		<input type="text" name="pet_hospital_address" value="<?php if(isset($pet_info)) echo $pet_info->hospital_address; ?>" class="textfield" placeholder="地址"/><br>
	        		<input type="text" name="pet_hospital_city" value="<?php if(isset($pet_info)) echo $pet_info->hospital_city; ?>" class="textfield" style='width:18%;margin-right:2%;' placeholder="城市"/>
	        		<input type="text" name="pet_hospital_district" value="<?php if(isset($pet_info)) echo $pet_info->hospital_district; ?>" class="textfield" style='width:18%;margin-right:2%;' placeholder="鄉鎮市區"/>
	        		<input type="text" name="pet_hospital_postal" value="<?php if(isset($pet_info)) echo $pet_info->hospital_postal; ?>" class="textfield" style='width:18%;margin-right:2%;' placeholder="郵遞區號"/>
	        		<input type="text" name="pet_hospital_country" value="<?php if(isset($pet_info)) echo $pet_info->hospital_country; ?>" class="textfield" style='width:19%;' class="textfield" placeholder="國家"/>
				</div>
			</div>
			
		    <div class='submit_div'>
				<button type="submit" class="button" style="">存檔</button>
			</div>
		</div>
			
	</form>
		
	<form action="/device/updateHuman" method="post">
	
		<input type='hidden' name='serial_number2' value='<?php echo $device->serial_number; ?>'/>
	
		<div id="updateHuman">
			<div id="humanInfo_container" class='container'>
				<div class="green_text">資料編輯</div>
				<div class='input_div'>
					<div class="blue_text"><font color="red">*</font>姓名</div>
	        		<input type="text" name="human_firstname" value="<?php if(isset($human_info)) echo $human_info->firstname; ?>" class="textfield" placeholder="名" required/>
	        		<input type="text" name="human_lastname" value="<?php if(isset($human_info)) echo $human_info->lastname; ?>" class="textfield" placeholder="姓" required/>
				</div>
				<div class='input_div'>
					<div class="blue_text"><font color="red">*</font>暱稱</div>
	        		<input type="text" name="human_nickname" value="<?php if(isset($human_info)) echo $human_info->nickname; ?>" class="textfield" required/>
				</div>
				<div class='input_div'>
					<div class="blue_text"><font color="red">*</font>性別
	        		<input type="radio" name="human_sex" value="m">男
					<input type="radio" name="human_sex" value="f">女</div>
				</div>
				<div class='input_div'>
					<div class="blue_text">生日</div>
	        		<input type="text" name="human_birthday" value="<?php if(isset($human_info)) echo $human_info->birthday; ?>" class="textfield datepicker"/>
				</div>
				<div class='input_div'>
					<div class="blue_text">身高(cm)</div>
	        		<input type="text" name="human_height" value="<?php if(isset($human_info)) echo $human_info->height; ?>" class="textfield"/>
				</div>
				<div class='input_div'>
					<div class="blue_text">體重(kg)</div>
	        		<input type="text" name="human_weight" value="<?php if(isset($human_info)) echo $human_info->weight; ?>" class="textfield"/>
				</div>
				<div class='input_div'>
					<div class="blue_text">血型</div>
	        		<input type="text" name="human_bloodtype" value="<?php if(isset($human_info)) echo $human_info->bloodtype; ?>" class="textfield"/>
				</div>
				<div class='input_div'>
				
	        		<table class='checkbox_table'>
	        			<tr>
	        				<th rowspan=4 style='vertical-align: top;'><div class="blue_text">疾病</div></th>
	        			</tr>
	        			<tr>
	        				<td><input type="checkbox" name="human_disease[]" value="心臟病" <?php if(strpos($human_info->disease,'心臟病') !== false) echo 'checked="checked"'; ?>>心臟病</td>
	        				<td><input type="checkbox" name="human_disease[]" value="高血壓" <?php if(strpos($human_info->disease,'高血壓') !== false) echo 'checked="checked"'; ?>>高血壓</td>
	        			</tr>
	        			<tr>	
	        				<td><input type="checkbox" name="human_disease[]" value="糖尿病" <?php if(strpos($human_info->disease,'糖尿病') !== false) echo 'checked="checked"'; ?>>糖尿病</td>
	        				<td><input type="checkbox" name="human_disease[]" value="失智" <?php if(strpos($human_info->disease,'失智') !== false) echo 'checked="checked"'; ?>>失智</td>
	        			</tr>
	        			<tr>
	        				<td colspan=2>
	        					<div style='float:left;'><input type="checkbox" name="human_disease[]" value="其他">其他</div>
	        					<input type="text" name="human_disease[]" value="" class='textfield' style='float:left;width:50%;font-size:0.5em;margin-left:5%;'/>
	        				</td>
	        			</tr>
	        		</table>
				</div>
				<div class='input_div'>
	        		<table class='checkbox_table'>
	        			<tr>
	        				<th rowspan=4 style='vertical-align: top;'><div class="blue_text">肢體障礙</div></th>
	        			</tr>
	        			<tr>
	        				<td><input type="checkbox" name="human_disability[]" value="行動" <?php if(strpos($human_info->disability,'行動') !== false) echo 'checked="checked"'; ?>>行動</td>
	        				<td><input type="checkbox" name="human_disability[]" value="聽覺" <?php if(strpos($human_info->disability,'聽覺') !== false) echo 'checked="checked"'; ?>>聽覺</td>
	        			</tr>
	        			<tr>	
	        				<td><input type="checkbox" name="human_disability[]" value="視覺" <?php if(strpos($human_info->disability,'視覺') !== false) echo 'checked="checked"'; ?>>視覺</td>
	        				<td><input type="checkbox" name="human_disability[]" value="語言" <?php if(strpos($human_info->disability,'語言') !== false) echo 'checked="checked"'; ?>>語言</td>
	        			</tr>
	        			<tr>
	        				<td colspan=2>
	        					<div style='float:left;'><input type="checkbox" name="human_disability[]" value="其他">其他</div>
	        					<input type="text" name="human_disability[]" value="" class='textfield' style='float:left;width:50%;font-size:0.5em;margin-left:5%;'/>
	        				</td>
	        			</tr>
	        		</table>
				</div>
				<div class='input_div'>
					<div class="blue_text">服用藥物</div>
					<textarea type="number" name="human_medications" value="<?php if(isset($human_info)) echo $human_info->medications; ?>" class="textfield" rows=3></textarea>
				</div>
				<div class='input_div'>
					<div class="blue_text">專屬醫院</div>
	        		<input type="text" name="human_hospital_name" value="<?php if(isset($human_info)) echo $human_info->hospital_name; ?>" class="textfield" placeholder="醫院名稱"/><br>
	        		<input type="number" name="human_hospital_phone" value="<?php if(isset($human_info)) echo $human_info->hospital_phone; ?>" class="textfield" placeholder="醫院電話"/><br>
				</div>
				<div class='input_div'>
	        		<div class="blue_text">醫院地址</div>
	        		<input type="text" name="human_hospital_address" value="<?php if(isset($human_info)) echo $human_info->hospital_address; ?>" class="textfield" placeholder="地址"/><br>
	        		
	        		<input type="text" name="human_hospital_city" value="<?php if(isset($human_info)) echo $human_info->hospital_city; ?>" placeholder="城市" class="textfield" style='width:18%;margin-right:2%;'/>
	        		<input type="text" name="human_hospital_district" value="<?php if(isset($human_info)) echo $human_info->hospital_district; ?>" placeholder="鄉鎮市區" class="textfield" style='width:18%;margin-right:2%;'/>
	        		<input type="text" name="human_hospital_postal" value="<?php if(isset($human_info)) echo $human_info->hospital_postal; ?>" placeholder="郵遞區號" class="textfield" style='width:18%;margin-right:2%;'/>
	        		<input type="text" name="human_hospital_country" value="<?php if(isset($human_info)) echo $human_info->hospital_country; ?>" class="textfield" placeholder="國家" style='width:19%;'/><br>
				</div>
			</div>
			
		    <div class='submit_div'>
				<button type="submit" class="button" style="">存檔</button>
			</div>
		</div>
		
	</form>
		
	<form id="updateValuable" action="/device/updateValuable" method="post">
	
		<input type='hidden' name='serial_number3' value='<?php echo $device->serial_number; ?>'/>
	
		<div class='container'>
			<div class="green_text" style='margin-bottom:3%;'>資料編輯</div>
			<div class='input_div'>
				<div class="blue_text"><font color="red">*</font>商品名稱</div>
        		<input type="text" name="valuable_name" value="<?php if(isset($valuable_info)) echo $valuable_info->name; ?>" class="textfield" required/>
			</div>
			<div class='input_div'>
				<div class="blue_text">特徵/敘述</div>
        		<textarea type="text" name="valuable_description" value="<?php if(isset($valuable_info)) echo $valuable_info->description; ?>" class="textfield" rows=3></textarea>
			</div>
		</div>
		<div class='submit_div'>
			<button type="submit" class="button" style="">存檔</button>
		</div>
	</form>
</div>
	
<script>
	var device_type = "<?php echo $device->type; ?>";
</script>

	</body>
</html>
