<link rel="stylesheet" type="text/css" href="/css/device_update_index.css?rand=<?php echo rand(); ?>">
<script type='text/javascript' src='/js/jquery-1.11.3.min.js'></script>
<script type='text/javascript' src='/js/jquery.form.js'></script>
<script type='text/javascript' src='/js/jquery.validate.js'></script>
<script type='text/javascript' src='/js/jquery.blockUI.js'></script>
<script type='text/javascript' src='/js/device_update_index.js?rand=<?php echo rand(); ?>'></script>
<ul id='title'>
	<li><a href='/'>首頁</a></li>
	<li> > </li>
	<li><a href='/user/index?serial_number=<?php echo $device->serial_number; ?>'>管理名單</a></li>
	<li> > </li>
	<li style='color:#86c557;'><?php echo $device->name; ?></li>
</ul>
<div id='device_menu_container'>
	<!-- <div class="blue_text title">照片</div>  -->
	<input type='hidden' name='serial_number' value='<?php echo $device->serial_number; ?>'/>
	<div>
		<form id='update_photo_form' method='post' action='/device/updatePhoto' style='visibility:hidden;'>
			<input type='file' name="photos" class="photos"/>
			<input type='hidden' name='serial_number' value='<?php echo $device->serial_number; ?>'/>
		</form>
		<div id='img_wrapper'>
			<div style='margin:0 auto;position:relative;'>
				<img id="pic" src= "
					<?php
						if(empty($device->photo)) {
							switch($device->type) {
								case "Pets":
									echo '/img/default-01.png';
									break;
								case "Human":
									echo '/img/default-02.png';
									break;
								case "Valuables":
									echo '/img/default-03.png';
									break;
								default:
									break;
							}
						}
						else echo $device->photo;
					?>"/>
				<img id='upload_btn' src="/img/14/pic-01.png" />
			</div>
		</div>
		<div id='info_wrapper'>
			<p class='green_text' style='font-size:6em;margin-top:0.7em;'><?php echo $device->name ?></p>
			<p class='green_text' style='font-size:3.5em;margin-top:-.5em;'>
				<?php
					//determine 'kind' from serial number
					$kind = '';
					
					if(!empty($device->serial_number))
						$kind = $device->serial_number[2];
					
					switch($kind){
						case "Q":
							$kind = "Qtag";
							break;
						case "B":
							$kind = "Btag";
							break;
						case "N":
							$kind = "Ntag";
							break;
						default:
							break;
					}
					
					echo $kind;
				?>
			</p>
			<p class='green_text' style='font-size:3.5em;margin-top:-.5em;'>ID: <?php echo substr($device->serial_number, 5, 14); ?></p>
		</div>
		<!-- 
		<div class='device_status'>
			<p class='green_text' style='font-size:4em;margin-top:0.2em;'>
			<?php
				switch($device->status){
					case "invalid":
						echo '停用';
						break;
					case "lost":
						echo '遺失';
						break;
					case "normal":
						echo '正常';
						break;
					default:
						echo '';
						break;
				}
			?></p>
		</div>
		 -->
		<div class="clear"></div>
	</div>
	<div class="blue_text" style='margin:5% 0 5% 0; float:left;'>狀態:</div>
	<div class="green_text" style='margin:5% 0 5% 2%; float:left;'>
		<?php
			switch($device->status){
				case "invalid":
					echo "<font style='color:EB447E;'>" . '停用' . "</font>";
					break;
				case "lost":
					echo "<font style='color:EB447E;'>" . '遺失' . "</font>";
					break;
				case "normal":
					echo '正常';
					break;
				default:
					echo '';
					break;
			}
		?>
	</div>
	<div class="clear"></div>
	<!-- 
	<div class="blue_text" style='margin:5% 0 5% 0; float:left;'>用途分類</div>
	<div class="green_text" style='margin:5% 0 5% 7%; float:left;'>
		<?php
			//determine 'type' from serial number
			$type = '';
			
			if(!empty($device->serial_number))
				$type = $device->serial_number[0];
			
			switch($type){
				case "P":
					$type = "寵物";
					break;
				case "M":
					$type = "人";
					break;
				case "T":
					$type = "物品";
					break;
				default:
					break;
			}
			
			echo $type;
		?>
	</div>
	<div class="clear"></div>
	-->
	<div style="margin-bottom:3em;">
		<font style="color:red;font-size:3.333em;float:left;">*</font><span class="blue_text" style='margin-right:5%;float:left;'>資料公開</span>
		<div class="open" style="margin-top:0.5em;float:left;">
		    <input type="checkbox" name="open" class="open-checkbox" id="myopen" value='y' <?php if($device->open == 'y') echo 'checked';?>>
		    <label class="open-label" for="myopen">
		        <span class="open-inner"></span>
		        <span class="open-switch"></span>
		    </label>
		</div>
		<div class="clear"></div>
	</div>
	<br>
	<div>
		<font style="color:red;font-size:3.333em;float:left;">*</font><span class="blue_text" style='margin-right:5%;float:left;'>遺失狀態</span>
		<div class="status" style="margin-top:0.5em;float:left;">
		    <input type="checkbox" name="status" class="status-checkbox" id="mystatus" value='lost' <?php if($device->status == 'lost') echo 'checked';?>>
		    <label class="status-label" for="mystatus">
		        <span class="status-inner"></span>
		        <span class="status-switch"></span>
		    </label>
		</div>
		<div class="clear"></div>
	</div>
	<!-- 
	<div>
		<font style="color:red;font-size:3.333em;">*</font><span class="blue_text" style='margin-right:5%;'>資料公開</span>
		<input type="radio" name="open" value="y" <?php if($device->open == 'y') echo 'checked';?>><span class='radio_text'>公開</span>
		<input type="radio" name="open" value="n" <?php if($device->open != 'y') echo 'checked';?>><span class='radio_text'>關閉</span>
	</div>
	<br>
	<div>
		<font style="color:red;font-size:3.333em;">*</font><span class="blue_text" style='margin-right:5%;'>遺失狀態</span>
		<input type="radio" name="status" value="lost" <?php if($device->status == 'lost') echo 'checked';?>><span class='radio_text'>遺失</span>
		<input type="radio" name="status" value="normal" <?php if($device->status != 'lost') echo 'checked';?>><span class='radio_text' >關閉</span>
	</div>
	 -->
</div>

<div>
	<a class='menu' href="/guestbook/list?serial_number=<?php echo $device->serial_number?>">
		<img src="/img/bu-01.png" style="width:100%;">
			<?php if($notification_count > 0 ) { ?>
			<span id='notification_count'><?php echo $notification_count; ?></span>
			<?php } ?>
			<span style="position:absolute;bottom:20px;right:10%;font-size:5em;" class="white_text">訊息通知</span>
	</a>
	<a class='menu'  href="/device/updateInfo?serial_number=<?php echo $device->serial_number?>">
		<img src="/img/bu-02.png" style="width:100%;">
		<div style="position:absolute;bottom:20px;right:10%;font-size:5em;" class="white_text">基本資料</div>
	</a>
	<div class="clear"></div>
</div>

<div>
	<a class='menu'  href="/photo/list?serial_number=<?php echo $device->serial_number?>">
		<img src="/img/bu-03.png" style="width:100%;">
		<div style="position:absolute;bottom:20px;right:10%;font-size:5em;" class="white_text">相片集</div>
	</a>
	<a class='menu'  href="/device/updateLostContact?serial_number=<?php echo $device->serial_number?>">
		<img src="/img/bu-04.png" style="width:100%;">
		<div style="position:absolute;bottom:20px;right:10%;font-size:5em;" class="white_text">遺失設定</div>
	</a>
	<div class="clear"></div>
</div>
