<!DOCTYPE html>
<html>
	<head>
		<title>Baby Search - Update Status</title>
		<link rel="stylesheet" type="text/css" href="/css/index.css">
		<link rel="stylesheet" type="text/css" href="/css/device_update_info.css?rand=<?php echo rand(); ?>">
	</head>

	<body>
		<ul id='title'>
			<li><a href='/'>首頁</a></li>
			<li> > </li>
			<li><a href='/device/index?serial_number=<?php echo $device->serial_number; ?>'>管理名單</a></li>
			<li> > </li>
			<li><a href='/device/update?serial_number=<?php echo $device->serial_number; ?>'><?php echo $device->name; ?></a></li>
			<li> > </li>
			<li style='color:#86c557;'>遺失設定</li>
		</ul>
		
		<div id="status_form_container" style="margin-left:36px;margin-right:36px;margin-top:64px;margin-bottom:120px;">
			
			<div class="green_text">遺 失 設 定</div>
			<article class="black_text" style="margin-top:3%;margin-bottom:5%;">
				請詳細提供遺失的相關線索，能幫助你盡快找回
			</article>
			
			<form action="" method="post">
			    <div class='input_div'>
			        <div class="blue_text"><font color="red">*</font>公告訊息</div>
			        <textarea type="text" name="message" class="textfield" placeholder="您可以描述遺失當時的情境，或是其他能協尋的重要線索" required></textarea>
			    </div>		    
			    <div class='input_div'>
			        <div class="blue_text">日期</div>
			        <input type="date" name="date" class="textfield" />
			    </div>
			    <div class='input_div'>
			        <div class="blue_text">時間</div>
			        <input type="time" name="time" class="textfield" />
			    </div>
			    <div class='input_div'>
			        <div class="blue_text"><font color="red">*</font>遺失地點</div>
			        <input type="text" name="location" class="textfield" placeholder="請填寫地點或明顯的景點建築" required/>
			    </div>
			    <div class='input_div'>
			        <div class="blue_text"><font color="red">*</font>穿著/特徵</div>
			        <textarea type="text" class='textfield' rows=3 name="description" placeholder="關於竉物的大小事..."></textarea>
			    </div>
			    <div class='input_div'>
			        <div class="blue_text" style="float:left;"><font color="red">*</font>聯絡人</div>
			        <a href="/lostcontacts/update">
			        	<div class="red_text" style="float:right;">編輯清單</div>
			        	<div style="margin-right:1%;float:right;"><img src='/img/12/icon-01.png'/></div>
			        </a>
			        <div class="clear"></div>
			        <!-- when print textarea, echo nl2br($message); -->
			        <div class="grey_text"><input type="radio" name="contact1" checked/>聯絡人1</div>
			        <div class="grey_text"><input type="radio" name="contact2"/>聯絡人2</div>
			        <div class="grey_text"><input type="radio" name="contact3"/>聯絡人3</div>
			    </div>     
			    <div class='submit_div'>
					<button type="submit" class="button" style="">儲存</button>
				</div>  
			</form>
		</div>
	</body>
</html>