<!DOCTYPE html>
<html>
	<head>
		<title>Baby Search - Mobile</title>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css" href="/css/index.css?rand=<?php echo rand(); ?>">
		<script type='text/javascript' src='/js/jquery-1.11.3.min.js'></script>
		<script type='text/javascript' src='/js/index.js?rand=<?php echo rand(); ?>'></script>
	</head>

	<body>
		<div style="background-color: white; box-shadow: 0 2px 10px 0.5px black;">
		<div style="position:fixed;left:20px;top:20px;"><img id="pclogo" src='/img/Icon.png'/></div>
		<!-- <div style="position:fixed;left:4%;top:65%;background-color:#666666;z-index:-1;"><img id="background" src='/img/background.png'/></div>  -->
		<div id="usermenu">
			<a href=""><img src="/img/button(1).png" id="cross_btn"/></a>
			<div class="clear"></div>
			<div id="space"></div>
			<a href="/user/update"><div id="userinfo_link">個人資訊</div></a>
			<a href="/user/updateContact"><div id="contact_link">聯絡人清單</div></a>
		</div>	
		<?php if(!isset($_GET['source'])) { ?>
		<div id="header">
			<?php if(isset($_SESSION) && !empty($_SESSION)) { ?>
			<a href="/user/login"><img src="/img/logo(white).png"/></a>
			<div id='logout'><a id="userlink" href="#usermenu"><?php echo $_SESSION['USER']['INFO']['nickname']?></a> / <a href='/user/logout'>登出</a></div>
			<?php } ?>
		</div>
		<?php } ?>
	
		<div id='content'>
		<?php echo $this->getContent() ?>
		</div>
		<div class='clear'></div>
		
		<?php if(!isset($_GET['source'])) { ?>
		<div id="footer">
			<p class="center">© 2015 Baby Search</p>
		</div>
		<?php } ?>
		
		<div class='clear'></div>
	</body>
</html>