<!DOCTYPE html>
<html>
	<head>
		<title>Baby Search - Mobile</title>
		<link rel="stylesheet" type="text/css" href="/css/index.css?rand=<?php echo rand(); ?>">
		<script type='text/javascript' src='/js/jquery-1.11.3.min.js'></script>
		<script type='text/javascript' src='/js/index.js?rand=<?php echo rand(); ?>'></script>
	</head>

	<body>
		<div id="usermenu">
			<a href=""><img src="/img/button(1).png" style="float:right;margin-top:2.5em;margin-right:5%;"/></a>
			<div class="clear"></div>
			<div style="font-size:8em;padding:2%;border-bottom: 1px solid white;"></div>
			<a href="/user/update"><div style="font-size:6em;padding:3%;border-bottom: 1px solid white;">個人資訊</div></a>
			<a href="/user/updateContact"><div style="font-size:6em;padding:3%;border-bottom: 1px solid white;">聯絡人清單</div></a>
		</div>	
	
		<div id="header">
			<a href="/user/login"><img src="/img/logo(white).png"/></a>
			<?php if(isset($_SESSION['USER'])) { ?>
			<div id='logout'><a id="userlink" href="#usermenu"><?php echo $_SESSION['USER']['INFO']['nickname']?></a> / <a href='/user/logout'>登出</a></div>
			<?php } ?>
		</div>
	
		<?php echo $this->getContent() ?>
		
		<div id="footer">
			<p class="center">© 2015 Baby Search</p>
		</div>
		
		<div class='clear'></div>
	</body>
</html>