<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<link rel="stylesheet" type="text/css" href="/css/index.css?rand=<?php echo rand(); ?>">

<div id="header">
	<a href="/user/login"><img src="/img/logo(white).png"/></a>
	<!-- <div id='logout'><a id="userlink" href="#usermenu"><?php echo $_SESSION['USER']['INFO']['nickname']?></a> / <a href='/user/logout'>登出</a></div>  -->
</div>
		
<?php 
			if(!empty($bulletins)) {
		
				$counter = 0;
			
				foreach($bulletins as $bulletin) {
					
					if($counter == 1) {
						echo <<<EOT
<div id="text" style="margin-top:1em; margin-bottom:2em; margin-right:1.5em;">
	<p class="green_text" style="text-align:left;margin:1em 1.2em;">其他公告訊息</p>
	<ul style='list-style-type:none;font-size:15px;'>
EOT;
					}
					
					if($counter > 0) {
					
						if($counter%2 == 0)
							echo <<<EOT
		<li class="odd" style='padding:10% 0;' >
{$bulletin->created}
<div class='bulletin_message'>
<div style='color:#86C557;text-align:left;margin-top:1em;'>公告 :</div><br>
{$bulletin->message}
</div> 		
		</li>
EOT;
						else
							echo <<<EOT
		<li class="even">
{$bulletin->created}
<div class='bulletin_message'>
<div style='color:#86C557;text-align:left;margin-top:1em;'>公告 :</div><br>
{$bulletin->message}
</div>
		</li>
EOT;
					}
					
					$counter++;
				}
				
				echo <<<EOT
</ul>
</div>
EOT;
			}
			
		?>
		
		<a href="history.go(-1);"><div style="margin-top:2%;background:#EB9F4E;font-size:4.167em;color:white;text-align:center;padding:5% 2%;">回上一頁</div></a>