<link rel="stylesheet" type="text/css" href="/css/index.css?rand=<?php echo rand(); ?>">
<link rel="stylesheet" type="text/css" href="/css/user_index.css?rand=<?php echo rand(); ?>">
<div id="user_container">
	<div id="user_pic_wrapper">
		<?php 
		if(!empty($user->photo))
			echo "<img src='" . $user->photo . "'  style='width:100%'></img>";
		else
			echo "<img src='/img/06/pic-01.png'  style='width:100%'></img>";
		?>
	</div>
	<div id="user_info_wrapper">
		<div class="green_text" id='user_info'>
			<?php
				if(!empty($device_list)) {
					//echo "歡 迎 回 來 ，" . $user['nickname'];
					echo "歡 迎 回 來 ，" . $user->nickname;
				}
				else {
					//echo "歡 迎 你 ，" . $user['nickname'];
					echo "歡 迎 你 ，" . $user->nickname;
				}
			?>
		</div>
		<a id='update_info_link' href="/user/update" class='blue_text'>
			<img src='/img/06/bu-02.png'/>	<?php echo $user->nickname?> <?php //echo $user['nickname']?>
		</a>
	</div>
	<div class="clear"></div>
</div>

<div id="addDevice_container">
	<div class="green_text title">管 理 名 單</div>
	<a href="/device/create" id='create_device_btn'>
			<img src="/img/06/bu-01.png"/>
	</a>
	<div class="grey_text">
		<?php
			if(!empty($device_list)) {

				echo "新增註册商品";

			}
			else {

				echo "你可以按 [ <img src='/img/06/icon.png'></img> ]開始新增註册你所購買的產品";
			}
		?>
	</div>
	<div class="clear"></div>
</div>

<div id="device_container">
	<?php
		if(!empty($device_list)) {
			
			echo "<div id='list_device'>";

			foreach($device_list as $k => $device) {
				$class = $k%2 == 0 ? "odd" : "even";
				$kind = '';
				
				$img = "";
				
				if(!empty($device->serial_number))
					$kind = $device->serial_number[2];


				switch($device->type) {
					case "Pets":
						if(empty($device->photo))
							$img = "<img src= '/img/17/pic-02-02.png'/>";
						else
							$img = "<img src= '{$device->photo}'/>";
						break;
					case "Human":
						if(empty($device->photo))
							$img = "<img src= '/img/17/pic-01-02.png'/>";
						else
							$img = "<img src= '{$device->photo}'/>";
						break;
					case "Valuables":
						if(empty($device->photo))
							$img = "<img src= '/img/17/pic-03-02.png'/>";
						else
							$img = "<img src= '{$device->photo}'/>";
						break;
					default:
						break;
				}
				
				switch($kind){
					case "Q":
						$kind = "Q Tag";
						break;
					case "B":
						$kind = "B Tag";
						break;
					case "N":
						$kind = "N Tag";
						break;
					default:
						break;
				}
				
				$notification_div = "";
				
				if($device->notification_count > 0)
					$notification_div = "<a href='/guestbook/list?serial_number={$device->serial_number}' class='notification'>{$device->notification_count}</a>";
				

				if(!empty($device->photo))
					$img = "<img src= '{$device->photo}'/>";
				echo <<<EOT
<a href='/device/update?serial_number={$device->serial_number}' class='device_wrapper'><li class='{$class}'>	
	<div class='img_wrapper'>	
		{$img}
		{$notification_div}
	</div>
	<div class='device_info'>
		<p class='green_text'>{$device->name }</p>
		<p class='green_text'>{$kind}</p>
		<p class='green_text'>USID : {$device->serial_number}</p>
	</div>
	<div class='clear'></div>
</a>
EOT;
			}
			
			echo "</div>";
		}
	?>
</div>
