<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<link rel="stylesheet" type="text/css" href="/css/index.css?rand=<?php echo rand(); ?>">
<link rel="stylesheet" type="text/css" href="/css/user_index.css?rand=<?php echo rand(); ?>">
<div id="user_container">
	<div id="user_pic_wrapper">
		<a href="/user/update">
		<?php 
		if(!empty($user->photo))
			echo "<img src='" . $user->photo . "'  style='width:100%'></img>";
		else
			echo "<img src='/img/06/pic-01.png'  style='width:100%'></img>";
		?>
		</a>
	</div>
	<div id="user_info_wrapper">
		<!-- 
		<div class="green_text" id='user_info'>
			<?php
				if(!empty($device_list)) {
					//echo "歡 迎 回 來 ，" . $user['nickname'];
					echo "歡 迎 回 來 ，" . $user->nickname;
				}
				else {
					//echo "歡 迎 你 ，" . $user['nickname'];
					echo "歡 迎 你 ，" . $user->nickname;
				}
			?>
		</div>
		 -->
		<a id='update_info_link' href="/user/update" class='black_text' style="width:50%;">
			<img src='/img/06/bu-02.png'/>	<?php echo $user->nickname?> <?php //echo $user['nickname']?>
		</a>
		<div style="margin-top:5%;margin-left:10%;margin-bottom:5%;">
			<a href="/user/update">
				<div class="black_text" style="text-decoration:none;float:left;">個人資訊</div>
			</a>
			<div class="black_text" style="float:left;">&nbsp&nbsp|&nbsp&nbsp</div>
			<a href="/user/updateContact" style="text-decoration:none;">
				<div class="black_text" style="float:left;margin-right:6.4%;">聯絡人資料</div>
			</a>
			<div class="clear"></div>
		</div>
	</div>
</div>

<div id="device_container">
	<?php
		if(!empty($device_list)) {
			
			echo "<div id='list_device'>";

			foreach($device_list as $k => $device) {
				$class = $k%2 == 0 ? "odd" : "even";
				$kind = '';
				
				$img = "";
				
				if(!empty($device->serial_number))
					$kind = $device->serial_number[2];


				switch($device->type) {
					case "Pets":
						if(empty($device->photo))
							$img = "<img src= '/img/default-01.png'/>";
						else
							$img = "<img src= '{$device->photo}'/>";
						break;
					case "Human":
						if(empty($device->photo))
							$img = "<img src= '/img/default-02.png'/>";
						else
							$img = "<img src= '{$device->photo}'/>";
						break;
					case "Valuables":
						if(empty($device->photo))
							$img = "<img src= '/img/default-03.png'/>";
						else
							$img = "<img src= '{$device->photo}'/>";
						break;
					default:
						break;
				}
				
				switch($kind){
					case "Q":
						$kind = "Qtag";
						break;
					case "B":
						$kind = "Btag";
						break;
					case "N":
						$kind = "Ntag";
						break;
					default:
						break;
				}
				
				$notification_div = "";
				
				if($device->notification_count > 0)
					$notification_div = "<a href='/guestbook/list?serial_number={$device->serial_number}' class='notification'>{$device->notification_count}</a>";
				

				if(!empty($device->photo))
					$img = "<img src= '{$device->photo}'/>";
				
				$id = substr($device->serial_number, 5, 14);
				
				if(!empty($device->name))
					$name = $device->name;
				else	
					$name = substr($device->serial_number, 11, 14);
				
				switch($device->status){
					case "invalid":
						$status = '停用';
						break;
					case "lost":
						$status = '遺失';
						break;
					case "normal":
						$status = '正常';
						break;
					default:
						$status = '';
						break;
				}
				
				echo <<<EOT
<div class='device_wrapper'><li class='{$class}'>	
	<div class='img_wrapper'>	
		{$img}
		{$notification_div}
		<p class='black_text' style='font-size:3.5em;text-align:center;margin-top:0;'>{$kind}</p>
	</div>
	
	<a href='/device/update?sn={$device->serial_number}'>
		<div class='device_info'>
			<p class='black_text' style='font-size:6em;margin-top:0.7em;'>{$name}</p>
			<p class='black_text' style='font-size:3.5em;margin-top:-.8em;'>ID : {$id}</p>
		</div>
		
		<div class='device_status'>
EOT;
			if($status == '遺失')
				echo "<p class='red_text' style='font-size:4em;'>" . $status . "</p>";
			else
				echo "<p class='black_text' style='font-size:4em;'>" . $status . "</p>";
			
			echo <<<EOT
		</div>
		<div class='clear'></div>
	</a>
	<div class='clear'></div>
	
</div>
EOT;
			}
			
			echo "</div>";
		}
	?>
</div>

<div id="addDevice_container">
	<div class="green_text title">管 理 名 單</div>
	<a href="/device/create" id='create_device_btn'>
			<img src="/img/06/bu-01.png"/>
	</a>
	<div class="default_text">
		<?php
			if(!empty($device_list)) {

				echo "新增註册Tag";

			}
			else {

				echo "你可以按 [ <img src='/img/06/icon.png' style='width:5%;'></img> ] 開始新增註册你所購買的Tag";
			}
		?>
	</div>
	<div class="clear"></div>
</div>
