<?php 
//for sso-login buttons

	$facebookLoginUrl = "https://www.facebook.com/dialog/oauth?"
			. "client_id=" . $config->facebook_sso->app_id
			. "&redirect_uri=" . $config->facebook_sso->redirect_url
			. "&state=" . md5(uniqid(rand(), TRUE))
			. "&response_type=code"
					. "&scope=user_about_me,email";

	$googleLoginUrl = "https://accounts.google.com/o/oauth2/auth?"
			. "client_id=" . $config->google_sso->client_id
			. "&redirect_uri=" . $config->google_sso->redirect_url
			. "&state=" . md5(uniqid(rand(), TRUE))
			. "&response_type=code"
					. "&scope=https://www.googleapis.com/auth/plus.login profile email" // openid%20profile
					. "&include_granted_scopes=true";

?>
<!DOCTYPE html>
<html>
	<head>
		<title>Baby Search - Login</title>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta name="viewport" content="width=device-width" />
		<link rel="stylesheet" type="text/css" href="/css/index.css">
		<link rel="stylesheet" type="text/css" href="/css/login.css">
		<script src="/js/jquery-1.11.3.min.js"></script>
		<script src="/js/jquery.form.js"></script>
		<script type='text/javascript' src='/js/login.js?rand=<?php echo rand(); ?>'></script>
	</head>

	<body>
		<div style="background-color: white; box-shadow: 0 2px 10px 0.5px black;">
		<div style="position:fixed;left:20px;top:20px;"><img id="pclogo" src='/img/Icon.png'/></div>
		<!-- <div style="position:fixed;left:4%;top:65%;background-color:#666666;z-index:-1;"><img id="background" src='/img/background.png'/></div> -->
		<div id="header">
			<img src="/img/logo(white).png"/>
		</div>
		
		<div id="banner_container">
			<img src="/img/pic-0-03.png"></img>
		</div>
		
		<div id="login_container">
			<a href="<?php echo $facebookLoginUrl; ?>">
				<div class='sso'>
					<img src="/img/01/bu-01.png"></img>
					<p>登入</p>
				</div>
			</a>
			<a href="<?php echo $googleLoginUrl; ?>">
				<div class='sso'>
					<img src="/img/01/bu-02.png"></img>
					<p style='color:#9B9B9B;'>登入</p>
				</div>
			</a>
			<div class="clear"></div>
		</div>
		
		<div id="newsfeed_container">
			<ul>
				<li style="font-size:3.333em;width:50%;">我們的消息</li>
				<li style='width:18%;margin-right:7%;'><a href='http://www.facebook.com/BabySearch' target='_blank'><img src='/img/01/icon-01.png'/></a></li>
				<li style='width:18%;'><a href='https://twitter.com/iPet_Tracker' target='_blank'><img src='/img/01/icon-02.png'/></a></li>
				<li style='width:55%;'></li>
			</ul>
		</div>
		<div id='download_container'>
			<ul>
				<li style="font-size:3.333em;width:50%;">APP下載</li>
				<li style='width:18%;margin-left:-5%;margin-right:7%;'><a href='http://www.tbpt.net/tw/js/babysearch/' target='_blank'><img src='/img/01/icon-03.png'/></a></li>
				<li style='width:18%;'><a href='https://play.google.com/store/apps/details?id=trace.com.babysearch' target='_blank'><img src='/img/01/icon-04.png'/></a></li>
				<li style='width:55%;'></li>
			</ul>
		</div>
		<div class="clear"></div>

		<article class="article">
			<div style="color:#86C557;text-align:center;">BabySearch 目標與精神</div>
			<hr style="background:#86C557;width:70%;height:0.05em;text-align:center;border:none;">
			<div style="color:#FFB330;text-align:center;">讓你的寶貝安心找到回家的路～</div>
			<div style="color:#FFB330;text-align:center;">這就是Babysearch協尋平台的目標</div><br>
			<div style="color:#333333;">我們認為＂協尋＂不單指產品能幫助使用者找尋你的寶貝也代表著使用者可以相互幫忙，發揮群體協助的力量BabySearch就是依循這個精神設計出來的使用者不但能透過BabySearch找到你遺失的寶貝也能透過BabySearch幫忙他人尋找他們的寶貝。</div>
		</article>
		
		<article class="bulletin" style="background:#F2F2F2;">
			<div style="color:#6D0000;text-align:center;">最新訊息</div><br>
			<div style="color:#333333;">BabySearch 2015/7/9 上線公開測試啟用至2015/9/31前本平台不計算費用年費開始日從2015/10/1起算測試有任何問題直接到babysearch粉絲團留言<br>
我們會立即修改~~~感謝~~<br>
FB粉絲團 :<br><i><a href="http://www.facebook.com/BabySearch" style="color:#007CFF;text-decoration:none;letter-spacing:0;">http://www.facebook.com/BabySearch</a></i><br>
			</div>
		</article>
		
		<div id="menuList_container">
			<ul>
				<li id="link1" class="odd">認 識 BabySearch</li>
				<div id="text1">
					<article class="article2">
						<h2 style="color:#86C557;">認識 BabySearch</h2>
BabySearch 是開放式的整合協尋平台 能全方位的協尋人、寵物、物品等你的寶貝事物目前支援Qr-code／NFC／BLE等技術產品分別命名為Qtag／Ntag／Btag。<br><br>
依使用者需求使用產品內建獨一無二的ID就如同為你的寶貝申請一張身份證。<br>
所有協尋動作就使用這個ID在雲端平台上面運作全世界智慧型手機都能幫助間接協尋。<br>
安裝Babysearch App 除能管理你的所有寶貝ID外更能主動選擇幫助他人協尋。</article>
				</div>
				<li id="link2" class="even">使 用 方 式</li>
				<div id="text2">
					<article class="article2">
						<h2 style="color:#86C557;">寵物 Qtag 使用方式</h2>
						<div style="color:#900000">Q:什麼是Qtag?</div>
您好，Qtag上的QR code是獨一無二的，就像專屬ID一樣若您的寵物有配戴Qtag又不幸在外流浪時，當善心人士看到牠，並刷取Qtag即可看到寵物資訊，主人也可在第一時間內知道有善心人士找到牠雙方再透過BabySearch平台進行交流，牠很快就可以回家囉!!<br><br>
						<div style="color:#900000">Q:如何購買Qtag</div>
您好，請前往各品牌官網，內有各經銷商資訊，歡迎參觀選購iPet Qtag 請前往iPet 官網<br>
						<i><a href="http://www.ipet-tracker.com/BabySearch" style="color:#86C557;text-decoration:none;letter-spacing:0;">http://www.ipet-tracker.com/BabySearch</a></i><br>
活動與訊息都會公布在 Facebook 粉絲團，請密切注意哦！<br><br>
						<div style="color:#900000">Q:購買產品後要去哪下載BabySearch APP?</div>
您好，到Google Play / App Store尋找”BabySearch”找到我們App 的logo 下載即可<br><br>
						<div style="color:#900000">Q:如何使用BabySearch APP進行Qtag資料新增及綁定?</div>
您好，請拿出手機，按照以下流程，就能給他牠它多一份保障。<br>
1.新增Qtag步驟：<br>
<div style="margin-left:1em;">1-1使用Google或FB帳號做登入</div>
<div style="margin-left:1em;">1-2點選左上角Tag 列表後，選讀取Tag</div>
<div style="margin-left:1em;">1-3選擇Qtag，鏡頭對準Qtag</div>
2.Qtag資料設定步驟：<br>
3.聯絡人資料設定步驟：<br>		
				</div>
				<li id="link3" class="odd">會 員 權 益 介 紹</li>
				<div id="text3">
					<article class="article2">
						<h2 style="color:#86C557;">會員權益介紹</h2>
各產品在銷售時已經內含一定時間的寵愛會員，當寵愛會員期限過期後，會變為一般會員。<br>
別擔心!一般會員，基本的協尋功能還是存在你可以依你需求選擇是否續約為寵愛會員！<br><br>
						<div style="color:#900000">(詳細寵愛會員期限與條款見各品牌產品介紹)</div><br>
						<img src="/img/membership.jpg" style="width:100%;"/>
				</div>
				<li id="link4" class="even">平 台 簡 介</li>
				<div id="text4">
					<article class="article2">
						<h2 style="color:#86C557;">平台簡介</h2>
						<div style="color:#900000">BabySearch所謂的開放式平台主要指?</div><br>
						<div style="color:#86C557">A: BabySearch App內崁Babysearch SDK (協尋公益套件)</div>
各團體只要提出申請即可在各App內安裝此套件讓App發揮群體協尋的功能。<br><br>
						<div style="color:#86C557">B:開放產品ID授權，各品牌產品能共用</div>
各品牌產品不需在花費精神在這方面透過少許授權費用取得ID，即可輕鬆將產品加入全功能的協尋功能。</article>
				</div>
				<li id="link5" class="odd">關 於 我 們</li>
				<div id="text5">
					<article class="article2">
						<h2 style="color:#86C557;">關於我們</h2>
恮欣科技成立於2009年台北，專注於協尋方面的技術其Tracker方面產品行銷歐美各地多年有感於市面上協尋技術零亂，且各行其事決定提出一協尋平台，讓各家協尋產品能整合集合各品牌與使用者的力量，發揮協尋的精神。<br><br>
恮欣科技是台灣少數從產品品牌，企畫，設計，硬體，軟體，雲端，App，生產，維修等都有能力自行處理的公司MIT更是我們的堅持，產品全程在台灣生產，雲端也設立在台灣恮欣科技的客戶，遍及全球，經由與當地經銷商合作，提供使用者優質且專業的售後服務。讓全球的消費者，都能體驗到最好的協尋產品及服務。</article>
				</div>
				<li id="link6" class="even">聯 絡 我 們</li>
				<div id="text6">
					<article class="article2">
						<h2 style="color:#86C557;">聯絡我們</h2>
若您使用上有任何的問題都歡迎向我們提出 不論友善的、憤怒的我們都欣然接受並且立刻處理若您有任何合作構想或願意加入 BabySearch 協尋平台都歡迎聯繫 。<br><br>
					<table>
						<tr>
							<td style="color:#86C557;">電話：</td>
							<td>(02)8791-1915</td>
						</tr>
						<tr>
							<td style="color:#86C557;">傳真：</td>
							<td>(02)8791-1915</td>
						</tr>
						<tr>
							<td style="color:#86C557;">電子郵箱：</td>
							<td style="color:Aqua;letter-spacing:0;">sales@traceez.com</td>
						</tr>
						<tr>
							<td style="color:#86C557;">地址：</td>
							<td>台北市11490內湖區成功路三段141號3樓 </td>
						</tr>
					</table>
					
					</article>
				</div>
				<li id="link7" class="odd">使 用 條 款</li>
				<div id="text7">
					<article class="article2">
						<h2 style="color:#86C557;">BabySearch網站服務與使用條款</h2>
						
1. 認知與接受<br>
感謝用戶選擇BabySearch（下稱B），B依照本【網站服務與使用條款】，包含【隱私權保護政策】、【手機服務使用條款】、【智慧財產權保護政策】（下稱本條款），提供用戶使用B之各項服務、網 站、或相關軟體應用程式（下稱B服務系統）。用戶請務必詳細閱讀本條款相關內容以保障權益；當用戶申請註冊B網站會員並開始 使用B服務系統時，視為已確實閱讀、瞭解並同意遵守本條款。 <br>
B有權隨時就本條款內容為修改、變更，建議用戶隨時注意本條款修改或變更內容。凡用戶於本條款為任何修改或變更後仍繼續使用B服務系統時，視為用戶已確實閱讀、瞭解並同意遵守該等修改或 變更。若用戶不同意本條款，或用戶所屬國家或地域排除本條款之全部或一部時，請勿使用B服務系統。<br>
若用戶未滿二十歲，除用戶本人應遵守上述規定外，並請用戶父母（或監護人）同時確實閱讀、瞭解並同意遵守本條款之所有內容，用戶方得使用或繼續使用B服務系統；當用戶於本條款為修改或變更後仍繼續使用B服務系統時，即推定用戶的父母（或監護人）亦已確實閱讀、瞭解並同意遵守本條款之修改或變更。<br><br>

2. 本條款的重大修改<br>
B偶爾可能認為需要對B服務系統和本條款作出修改或變更。如果B認為對本條款所做之修改或變更屬於重大修改者，B將通過B服務系統通知用戶。如果用戶於B做出修改或變更後仍繼續使用B服務系統，將被視為接受本條款之修改或變更的內容。<br><br>

3. 隱私權政策<br>
B非常重視用戶的隱私權，因此制訂了隱私權保護政策。關於用戶的會員註冊以及其他特定資料依B所制定的【隱私權保護政策】受到保護與規範。用戶了解當開始使用B服務系統時，即表示用戶同意B遵照【隱私權保護政策】進行對用戶個人資料的收集與使用，包括跨國間的傳輸與儲存及B及其關係企業內部之使用。故請用戶細讀B有關【隱私權保護政策】的內容。<br><br>

4. 享用BabySearch服務系統<br>
以下訊息能幫助用戶了解如何享用BabySearch服務系統。<br>
4.1 註冊服務<br>
用戶可選用“電腦註冊服務”或“智慧型手機服務”方式申請註冊登入BabySearch服務系統：<br>
4.2 註冊義務<br>
用戶理解並同意為能確保使用B服務系統，於申請註冊時同意提供真實正確、最新及完整的資料，並隨時更新其資料來源。若用戶提供任何錯誤、不實或不完整的資料，致用戶發生任何損害，B不負擔任何責任，同時，B有權暫停或終止用戶的帳號，並拒絕用戶使用B服務系統之全部或一部。<br>
4.3 免費與收費用戶<br>
用戶理解並同意B服務系統之基本服務為免費服務，故用戶不得就免費服務內容主張任何權利，B亦不負擔任何義務。唯用戶可選擇使用需另行付費之服務，其詳細收費服務內容請參考B服務系統任 何時候所公布之內容。<br>
4.4 退費<br>
依各經銷商規定申請退費，但申請退費時需同時退回發票或繳費憑證。<br><br>

5. 授權範圍與轉讓<br>
B服務系統及其提供的內容均屬於B或B服務系統。B服務系統允許用戶將B服務系統用於非商業的個人目的，並允許用戶於 所屬國家根據自己選擇之服務方式獲得B服務系統中提供的服務內容（下稱授權範圍）。本授權範圍的授權期間為用戶或B之其中一方提出終止。<br>
B軟體應用程序為授權給用戶使用，而並非出售給用戶。因此，即使用戶安裝了相關設備，B軟體應用程序的所有副本的所有權仍歸B所有。 B可以將本條款全部或一部內容不受任何限制地進行轉讓，但用戶不得將本條款全部或一部內容轉讓給任何第三方，也不得將本授權範圍內之權利轉讓或再授權給任何第三方。<br>
所有的B商標、證明（或團體）標章、團體商標、商品名稱、網域 名稱和B旗下品牌的任何其他表徵，均屬於B所有財產。用戶不可憑藉本授權範圍作為商業或非商業目的使用B商標、證明（或團體）標章、團體商標、商品名稱、網域名稱和B旗下品牌的任何其他表徵。<br>
用戶同意遵守B本條款第九條用戶的守法義務與承諾，且不會以任 何未經本條款明確授權之方式來使用B服務系統。<br><br>

6. 用戶內容<br>
用戶可以在B服務系統中發佈、上傳和/或提供（下稱發佈）內容，包括圖片、文字、播放列表編譯等（下稱用戶內容）。用戶須對其提供的任何用戶內容及其後果全權負責。用戶表示其有權利發佈在B服務系統中的任何用戶內容，且此類用戶內容，或者B在按照本條款的規定使用這些用戶內容的過程中：<br>
（a）沒有違反本條款、適用法律或他人的智慧財產權或公開權，或<br>
（b）在未經明確書面同意 的情況下，並不暗示B或任何品牌、實體或個人與用戶或用戶發佈之用戶內容存在任何附屬或合作關係，或表示認可和批准。對於用戶發佈的任何用戶內容，凡是通過B服務系統發佈的或者與B相關的， 用戶已授權B使用，且此類授權範圍具有非排他、可轉讓、再授權、無需支付授權金(或權利金)、在全球範圍內有效，以使B可 使用任何用戶發佈的用戶內容。以上授權範圍在用戶終止其B帳號之前將持續有效，除非用戶已經發佈、公開和/或與他人共享了用戶內容。除了本文特別授權的範圍之外，對於用戶在B服務系統發佈的用戶內容，其所有權利，包括智慧財產權等，均歸用戶所有。除非根 據用戶所屬國家或地域適用法律的規定，用戶同意放棄 自己的相關權利，包括放棄自己身為智慧財產權所有人的權利及在此類用戶內容受 到貶毀性處理時放棄提出異議的權利。<br>
B不會監視、審查或編輯用戶內容，但保留無理由或以任何理由刪除、禁止登入任何用戶內容的權利，包括但不限於B自行認為違反了本條款或本地國家法律規定的用戶內容。B採取這些行動時，無需提前通知用戶。我們有唯一裁量權決定是否刪除或禁止登入用戶內容。B不承諾會刪除或禁止登入任何特定的用戶內容。若用戶相信資料沒有違反規定，用戶可與B客服信箱聯繫並提出異議通知與相關文件，要求恢復已刪除內容或相關資訊，或恢復存取權。<br>
B對用戶內容不承擔任何責任，也不會對用戶內容發表任何觀點。假如用戶認為任何其他用戶內容侵犯了自己的智慧財產權的，請參酌 【智慧財產權保護政策】。假如用戶認為任何其他用戶內容沒有遵循第九條用戶的守法義務與承諾，或者用戶的權利在適用本地法律下受到任何其他用戶內容侵犯的，請與B客服信箱聯繫。<br><br>

7. 用戶對B的授權<br>
作為本條款B授權用戶使用的權利代價，用戶將授權我們以下權利：<br>
（a）允許B服務系統使用用戶設備上的處理器、寬頻和存儲硬體，以方便服務操作；<br>
（b）由B及其關係企業儲存或管理用戶內容，並由B及其關係企業之搜尋工具進行索引及抓取，並公開刊登、使用於B服務系統及其關係企業的相關系統網路上，包括但不限於B所聯盟或合作的夥伴網站上；<br>
（c）授權B及其關係企業 可以基於公益或為宣傳、推廣或經營B及本服務之目的，進行使用、修改、重製、公開播送、改作、散布、發行、公開發表、公開傳輸、公開上映、翻譯該等資料(用戶內容)，並得在此範圍內將前述權利轉授權第三人。用戶並保證B及其關係企業使用、修改、重製、 公開播送、改作、散布、發行、公開發表、公開傳輸、公開上映、翻 譯、轉授權用戶內容，不致侵害任何第三人之智慧財產權，否則應對B及其關係企業負損害賠償責任。<br>
用戶特別授權B具有非排他性、可轉讓、可再授權、無需支付授權金（或權利金）、特別授權金（或權利金）之權利，且在全球範 圍內永久有效，以使用、複製、公開、發佈、翻譯和發佈任何上傳在B服務系統上或通過B服務系統發佈的任何用戶內容。<br>
本文條款並非指授權予用戶和B以外的其他任何人，因此任何情況 下本文條款均不能作為任何第三方取得授權權利。如B未能依本文條款或本條款中的任何規定使用或履行，並不表示B放棄此類權利。<br><br>

8. 用戶的守法義務及承諾<br>
為了保證所有用戶均能享用B服務系統，B制定了幾條基本原則，供用戶在使用B服務系統的過程中遵守。用戶承諾絕不為任何非法目的或以任何非法方式使用本服務，並承諾遵守中華民國相關法規及一切使用網際網路之國際慣例。若係中華民國以外之用戶，並同意遵守所屬國家或地域之法令。同意並保證不得利用B服務系統從事侵害他人權益或違法之行為。<br>
請嚴格遵守履行這些原則，並鼓勵其他用戶也遵守履行。B嚴禁自己或用戶做出以下行為：<br>
（a）複製、重製、翻錄、記錄或公開B服務系統中向用戶提供的任何B服務系統或內容，或者使用本條款未明確得授權使用的B<br>
服務系統或內容；<br>
（b）於沒有合法權利下使用B服務系統來導入或複製任何本地或用戶所屬國家或地域之文件；<br>
（c）以B服務系統或其中的任何部分為基礎，反向製作、反向編譯、反向彙編、修改或創作衍生著作；<br>
（d）規避B、B的授權人或者任何第三方使用以保護可以通過B服務系統登入的內容的技術；<br>
（e）出租或租賃B服務系統中的任何部分；<br>
（f）規避B要求的任何區域限制；<br>
（g）以人為方式，或其他自動化流程來操作B服務系統；<br>
（h) 對於B服務系統中包含的，或者通過B服務系統提供的任何著作權、商標或其他智慧財產權，進行刪除或更改；<br>
（i）將用戶的密碼提供給任何其他人，或者使用任何其他人員的用戶帳號和密碼。<br>
請尊重B和B服務系統的用戶。請勿通過註冊和/或使用某個用戶帳號，在B服務系統中參與涉及以下內容的任何活動或者上傳含有以下訊息的用戶內容：<br>
 (a）具有攻擊、辱罵、誹謗、色情、淫穢性質或任何違反公共秩序或善良風俗或其他不法的文字、圖片或任何型式的檔案；<br>
（b）非法內容、蓄意縱容或做出任何性質的違法行為的內容，其包括但不限於：侵犯了B或第三方智慧財產權、隱私權或所有權的行為；<br>
（c） 違反依法律或契約所應負之保密義務；<br>
（d）含有惡意內容，包括惡意軟體、木馬、病毒或者會妨礙任何用戶登入B服務系統的內容或任何對電腦軟、硬體產生中斷、破壞或限制功能之程式碼之資料等；<br>
（e）意圖在騷擾或欺凌其他用戶，或者會騷擾或欺凌到其他用戶內容；<br>
（f）冒充或歪曲用戶與其他用戶、個人或實體的關係的內容，或者俱有欺騙、失實、欺詐、誤導等性質的內容；<br>
（g）使用自動化方式來虛假廣告內容；<br>
（h）涉及濫發來路不明的廣告郵件、垃圾郵件、連鎖信或類似郵件的內容，包括通過B的郵件信箱等方式；<br>
（i）涉及商業或銷售活動的內容，例如廣告、比賽、彩票抽獎、非法傳銷等；<br>
（j）推銷商業產品或服務的內容者；<br>
（k）干擾B服務系統的內容；干預或試圖探測、掃瞄或測試B服務系統、B電腦系統或伺服器或網路存在哪些缺陷的內容；違反B
     的任何安全或認證措施的內容等；<br>
（l）從事不法交易行為或張貼虛假不實、引人犯罪之訊息；<br>
 (m) 販賣槍枝、毒品、禁藥、盜版軟體或其他違禁物；<br>
 (n) 提供賭博資訊或以任何方式引誘他人參與賭博；<br>
 (o) 以任何方法傷害未成年人；<br>
 (p) 對於恐怖行動提供任何實質支持或資源；<br>
 (q) 追蹤他人或其他干擾他人或為前述目前蒐集或儲存他人之個人資訊；<br>
 (r) 其他B認為違反本條款的內容或行為。此外，用戶同意B可以以任何理由收回用戶的用戶帳號。<br>
在B上公開訊息時，請三思而行。 B服務系統包括社交和互動功能，包括上傳或/和發佈用戶內容、共享內容、公開某些個人資料以及其他在用戶的帳號設置中可以選擇的內容。請牢記：共享或公開的 信息可能被B或者網絡中的其他用戶拿來使用或轉發。因此，請謹慎使用B服務系統，並定期管理用戶的帳號設置。用戶可以自行選 擇在B服務系統中公開任何行動或信息，對此，B不承擔任何責任。<br><br>

9. 用戶帳號、密碼與安全<br>
用戶的密碼用來保護用戶的帳號。用戶應當對自己的密碼全權負責，確保密碼安全及保密。用戶明白在B服務系統中使用個人用戶帳號和密碼時，用戶應該自行承擔責任。如用戶帳號或密碼丟失或被盜，而用戶認為第三方在未經授權的情況下登入了用戶的帳號，請立即通知B，並儘快修改個人密碼。<br>
一旦輸入的用戶帳號及密碼與用戶所登錄資料一致時，無論是否由用戶本人親自輸入，均視為用戶所使用，即使係遭盜用、不當使用或其他B服務系統無法辨識是否為用戶本人親自使用的情況，B對此所致的損害不負擔任何責任。<br><br>

10. 技術限制及改良<br>
B將盡合理努力，確保B服務系統正常運作。但是，某些技術難題或維修操作可能造成系統不定時地臨時中斷。B有權修改或中止B服務系統的功能和特徵。這些修改或中止可以定期或在任意時間進行；可以是臨時或是永久修改或中止；可以提前通知或不發任何通知與用戶。但在任何情形下，對於中斷、修改或中止B服務系統或者系統中的任何功能或特徵的行為，B概不向用戶承擔任何責任。用戶理解並同意，B沒有義務維護、支援、提升或更新服務，也不負責透過B服務系統提供全部或部分具體內容。B對於用戶因使用（或無法使用）B服務系統而造成的損害，除故意或重大過失外，不負任何賠償責任。<br><br>

11. 有效期限及協議終止<br>
用戶或B提出終止之前，本條款對用戶而言將一直適用。如果用戶在未經授權的情況下使用了或被懷疑使用了B服務系統，或者沒有遵守本條款的相關規定，B可以隨時不經通知終止本條款或者終止用戶帳號、密碼或者臨時禁止用戶登入使用B服務系統，並將任何會員內容加以移除並刪除。如果用戶或者B終止了本條款，或者B暫時禁止用戶登入B服務系統，用戶同意B概不向用戶負擔任何責任。<br><br>

12. 責任限制<br>
用戶同意在適用法律之許可範圍之內，對於B服務系統、第三方應用程序或者第三方應用程序的內容中存在的任何問題或者不滿，用戶唯一及所有能夠採取的補救方法就是卸載任何B軟體、停止使用 B服務系統、第三方應用程序或者第三方應用程序中的內容。<br>
在法律允許的最大範圍之內，任何情形下，B及其高級職員、股 東、員工、代理人、董事、附屬公司、關聯公司、繼承人、受讓人、 供應商或許可人等，均不對以下內容負責：<br>
（a）因使用或無法使用B服務系統、第三方應用程序或第三方應用程序的內容而引起的任何間接損害、特殊損害、附帶損害、懲罰性損害、示範性損害或從屬性損害（包括喪失使用價值、數據、業務、利潤等），不考慮法學理論，無論B事先是否警告過可能出現這些損害，即使是沒有造成根 本意義上的損害；<br>
（b）與B服務系統、第三方應用程序、第三方應 用程序的內容相關的一切索賠之累計責任。<br><br>

13. 關於國際使用與進出口遵循事項之特別警告<br>
有鑑於網際網路的全球性，用戶同意遵守所有有關網路上行為及用戶所屬國家或地域之相關法令規範。對B服務系統的使用以及經由B服務系統所移轉、刊載及上傳之軟體、技術與其他技術資料皆可能受到美國與其他國家的進出口法律之管制。用戶同意遵守所有應適用之進出口法令規範，包括但不限於美國之出口管理規範及美國之制裁管理方案。<br><br>

14. 完整的協議<br>
本條款共同構成B與用戶達成全部條款與條件之完整合義，雙方之前就有關本條款的內容達成的所有相關協議，無論是以書面形式還是以口頭形式做出，均予以作廢。用戶通過書面形式或口頭方式向B提供的任何涉及本條款額外的或變更的條款或條件，均被視作無 效。用戶確認其沒有B在本條款之外所做的任何口頭或書面陳述以同意及接受協議。<br>
但是，請注意，用戶在使用B服務系統的過程中涉及到的其他方面可能應受到附加協議的管轄。在此類情形下，用戶應當另行同意其 他的條款與條件。另行同意的那些條款與條件僅管轄其對應適用的服務，而與本條款不同，是本條款的補充，不得取代本條款。另行同意的那些條款、條件與本條款發生矛盾者，應當以本條款為準，除非本條款中另有規定。<br>
用戶使用B服務系統期間，B可向用戶提供機會，邀請用戶透過B服務系統參加彩票抽獎、比賽、調查等活動 （下稱「特別促銷活動」）。特別促銷活動可能受到本條款以外的其他條款與條件的管轄。特別促銷活動的條款與條件與本條款間發生矛盾者，應以特別促 銷活動的條款與條件為準。<br><br>

感謝用戶閱讀本條款。希望用戶喜歡B服務系統。若有任何想法或疑義，歡迎隨時與B客服信箱聯繫，立即隨時協助處理與回覆說明。<br><br>

BabySearch 隱私權保護政策<br>
1. 認知與接受<br>
感謝用戶選擇BabySearch（下稱B），B依照本網站服務條款，且為了提供用戶更完整與妥善的B服務系統，B需要向用戶收集一些資料。以下條款內容為【隱私權保護政策】，目的係為告訴用戶，B需要收集哪些用戶資料、將如何使用用戶資料、如何管理和保存收集來的用戶資料等。用戶請務必詳細閱讀【隱私權保護政策】相關內容以保障權益；當用戶申請加入B網站會員並開始使用B服務系統時，視為已確實閱讀、瞭解並同意遵守【隱私權保護政策】，並同意B依照【隱私權保護政策】規定使用用戶資料。本聲明隨時可能會變更，請定期查詢。B將依法令及本聲明內容保護用戶對其個人資料之隱私權。若用戶不同意【隱私權保護政策】，或用戶所屬國家或地域排除本條款之全部或一部時，請勿使用B服務系統。<br><br>

2. 資料收集<br>
當用戶申請註冊使用B服務系統時，可能以多種方式從B服務系統的不同部分收集用戶個人資料，例如用戶的真實姓名、登入帳戶名、密碼、性別、國籍、出生日期、電子郵件信箱、身份證字號、聯絡住址、電話、職業和個人興趣等私密性之資料。<br><br>

3. 使用資料與目的<br>
B為提供更完善的服務系統，以及用戶可以完整使用B服務系統，B所收集到的用戶資料，包括用戶的個人資料等，將用於以下用途：<br>
（1）透過B服務系統、產品和其他服務方法，改善及為用戶帶來個人化的體驗；<br>
（2）確保B服務系統、產品和其他服務手段的技術功能，開發新的產品和服務，分析用戶如何使用B服務系統，包括用戶與應用程序、廣告宣傳、B服務系統中可用的產品和服務以及提供了鏈接或直接提供的產品和服務等；<br>
（3）針對用戶提供使用B服務系統反應的問題與用戶進行交流，包括但不限於廣告或促銷活動電子郵件或訊息；<br>
（4）啟用並推廣服務，包括但不限於B服務系統的特徵和內容，以及所提供的其他服務，如分享、用戶間互動、通知和建議、與第三方服務進行整合等；<br>
（5）履行本條款、【隱私權保護政策】、【智慧財產權條款】、【手機服務條款】等；<br>
（6）本條未提及但【隱私權保護政策】其他條款提及之其他使用用途。 <br>
B蒐集、處理及利用個人資料之特定目的包括但不限於：行銷業務、消費者、客戶管理與服務、消費者保護、國內外交流業務、智慧財產權、光碟管理及其他相關行政、資訊通訊服務、網路購物及其他電子商務服務、廣告和商業行為管理業務以及其他契約、類似契約或法律關係管理之事務或業務。 <br><br>

4. 分享資料<br>
B為提供更完善的服務系統，以及用戶可以完整使用B服務系統，B所收集到的用戶資料，包括用戶的個人資料等，不會任意揭露或出售、交換、或轉讓用戶的個人識別資料或任何用戶非公開性資料予第三人，除非經由用戶同意或法律規定。但關於用戶公開性資料，B分享使用於以下用途：<br>
4.1 查找其他B用戶並在B服務系統中進行分享<br>
4.2 在Facebook或其他服務中進行分享<br>
4.3 分享到第三方應用程序<br>
4.4 服務提供商及其他<br>
為能完整提供用戶使用B服務系統，可能需將用戶資料分享給B子公司或相關企業、或相關合作企業、或第三方服務提供商等。但B仍會遵照【隱私權保護政策】與相關法令規定。<br><br>

5. 用戶偏好設定<br>
用戶可透過使用B服務系統中關於個人化設定功能，自行設定選擇願意公開分享資料或願意提供B使用的資料等用戶偏好設定。唯特別提醒用戶，部分資料可能無法特定設定為非公開性資料，例如用戶的登入帳戶名、個人資料圖片、網絡社交關係等。因此，請注意並定期管理用戶的設定資料。<br><br>

6. 鏈接<br>
B可能會發佈或上傳來自任何第三方的廣告宣傳資訊或者鏈接到任何第三方網站的其他內容。B無法控制任何第三方的隱私保護措施或內容，也不對此承擔任何責任。若用戶希冀了解任何第三方如何收集和處理用戶的個人資料，煩請自行參閱他們所制定之隱私權保護政策。<br><br>

7. 安全<br>
B會盡最大努力確保用戶儲存於B服務系統中的用戶資料。唯網際網路資料的傳輸不能保證百分之百的安全，儘管B保護用戶的個人資料安全，仍無法確保用戶傳送或接收資料的安全。此風險並不在B所承擔的責任範圍內。為保障用戶隱私及安全，請妥善管理並保密用戶使用密碼，不要將任何個人資料，尤其是密碼提供給任何人，以保障用戶資料安全。同時，請選擇一個獨特及保密強度高的密碼，以限制他人進入用戶的電腦與瀏覽器。每次使用完B服務系統之後，請勿忘記安全登出系統。<br><br>

8. 登入並更新用戶資料<br>
B將保管儲存用戶資料至用戶或B終止服務為止。用戶有權在任何時候修改更新個人B帳號資料的權利，包括但不現於接受B通知促銷活動或收即、處理或使用用戶資料等決定。 <br><br>

如有任何看法與建議，請與BabySearch客服信箱聯繫，會盡速回覆與說明。<br><br></article>
						
				</div>
				<!-- 
				<li id="link8" class="even">隱 私 權 政 策</li>
				<div id="text8"></div>
				 -->
			</ul>
		</div>
		
		<div id="article_container">
			<p class='green'>聯絡我們</p>
			<p style="color:#4D4D4D;border-color:#4D4D4D;border-top-style:dotted;border-bottom-style:dotted;padding-top:3%;padding-bottom:3%;margin-bottom:0;">電話 : <a href="tel:028791-1915">(02)8791-1915</a></p>
			<p style="color:#4D4D4D;border-color:#4D4D4D;border-bottom-style:dotted;padding-top:3%;padding-bottom:3%;margin-top:0;">信箱 : <a href="mailto:sales@traceez.com">sales@traceez.com</a></p>
		</div>
		<!-- 
		<div id="newsfeed_container">
			<ul>
				<li style='width:25%;' class="table_green_text" style="font-size:3em;">我們的消息</li>
				<li style='width:10%;'><a href='http://www.facebook.com/BabySearch' target='_blank'><img src='/img/01/icon-01.png'/></a></li>
				<li style='width:10%;'><a href='https://twitter.com/iPet_Tracker' target='_blank'><img src='/img/01/icon-02.png'/></a></li>
				<li style='width:55%;'></li>
			</ul>
		</div>
		<div id='download_container'>
			<ul>
				<li style='width:25%;' class="table_green_text" style="font-size:3em;">APP下載</li>
				<li style='width:10%;'><a href='http://www.tbpt.net/tw/js/babysearch/' target='_blank'><img src='/img/01/icon-03.png'/></a></li>
				<li style='width:10%;'><a href='https://play.google.com/store/apps/details?id=trace.com.babysearch' target='_blank'><img src='/img/01/icon-04.png'/></a></li>
				<li style='width:55%;'></li>
			</ul>
		</div>
		 -->
		<br/><br/><br/><br/>
		
		<!-- 
		<h3>This is an ajaxform test</h3>
	
		<form id="ajaxform" action="index" method="POST">
			Name: <input type="text" id="formName" name="name" required/> <br/>
		    Email: <input type="email" id="formEmail" name="email" value="" required/> <br/>
		    <input type="submit" value="註册"/>
		</form>
		
		 
		
		<script>

        // wait for the DOM to be loaded 
        $(document).ready(function() { 

            // bind 'myForm' and provide a simple callback function 
            $('#ajaxform').ajaxForm({
				beforeSerialize:function(){
	                var formData = $("#formEmail").val();
	                var status = "";
	                
	                $.ajax({
		                async: false,
	    				url: '/user/checkEmailExists',
	    				type: "post",
	    				data: {"formKey" : formData},
	    				success: function(data) {
							if(data.status == 'success') {
								console.log("status return success");
								status = true;

								//stores email into SESSION upon successful login
								$_SESSION['email'] = formData;
							}
							else {
								console.log("status return fail");
								status = false;
							}
							
	        				/**
	        				console.log("success");
	        				var x;
	     
	    					for(i=0; i<data.length; i++) {

	    						x = data[i];
	    						//console.log(x["id"]);
	    						//console.log(x["name"]);
	    					}

	    					if(formData == x["name"])
	        					console.log("Sorry, user name '" + x["name"] + "' already existed in the system. " +
	                					"Please try another user name.");
	    					**/
	    				}
	    			});
	                //console.log(status);
	    			return status;
				},
				success:function() {
					console.log("success");
				}
            });
        });
	</script>
	-->
	
		<div id="footer">
			<p class="center">© 2015 Baby Search</p>
		</div>
		</div>
	</body>
</html>