<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<link rel="stylesheet" type="text/css" href="/css/index.css?rand=<?php echo rand(); ?>">
<link rel="stylesheet" type="text/css" href="/css/lost_devices.css?rand=<?php echo rand(); ?>">

<div id="lost_banner">
	<a href="/user/login"><img src="/img/logo(white).png"/></a>
	<!-- <div id='logout'><a id="userlink" href="#usermenu"><?php echo $_SESSION['USER']['INFO']['nickname']?></a> / <a href='/user/logout'>登出</a></div>  -->
</div>

<div id="lost_label">遺失公告
</div>

<?php 
			if(!empty($lost_devices)) {

				foreach($lost_devices as $device) {
?>
					<div id="lost_device_wrapper">
						<div id="lost_photo">
							<img src="<?php echo $device->photo?>"/>
						</div>
						<div id="lost_info_wrapper">
							<p class="lost_info_label">名稱:</p>
							<p class="lost_info><?php echo $device->name?></p>
							<div class="clear"></div>
							<p class="lost_info_label">時間:</p>
							<p class="lost_info><?php echo $device->lost_date?></p>
							<div class="clear"></div>
							<p class="lost_info_label">地點:</p>
							<p class="lost_info><?php echo $device->lost_location?></p>
							<div class="clear"></div>
							<p class="lost_info_label">敘述:</p>
							<p class="lost_info><?php echo $device->lost_message?></p>
							<div class="clear"></div>
						</div>
						<div class="clear"></div>
					</div>
		<?php
				}
			}		
		?>
		
		<a href="history.go(-1);"><div id="back">回上一頁</div></a>