<!DOCTYPE html>
<html>
	<head>
		<title>Baby Search - Update User</title>
		<link rel="stylesheet" type="text/css" href="/css/index.css">
		<link rel="stylesheet" type="text/css" href="/css/user_update.css">
		<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
		<script src="/js/jquery-1.11.3.min.js"></script>
		<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
		<script src="/js/jquery.form.js"></script>
	</head>

	<body>
		<div class="header">
			<img src="/img/02/logo(white).png"></img>
			<ul style="float:right;margin-right:36px;">
				<a href=""><li><?php echo $user->nickname ?></li></a>/
				<a href=""><li>登出</li></a>
			</ul>
			<div class="clear"></div>
		</div>
		
		<div style="height:110px;line-height:110px;padding-left:36px;padding-right:36px;background:#D9D9D9;">
			<font class="grey_text">首 頁 > </font>
			<font class="green_text">編 輯 個 人 資 訊</font>
		</div>
		
		<div id="user_form_container" style="margin-top:64px;margin-bottom:120px;margin-left:36px;margin-right:36px;">
			<form action="/user/update" method="post" id='update_user_form' enctype="multipart/form-data">
				<div class="blue_text" style="font-size:64px;">我的個人照片</div>
				<div style='height:250px;width:250px;margin:0 auto;position:relative;'>
					<img class="blah" src= "<?php echo $user->photo?>" style="width:100%;"/>
					<img class='upload_btn' src="/img/14/pic-01.png" style="position:absolute;top:0px;"/>
					<input type='file' name="photos" class="photos"/>
				</div>
					
				<div class="blue_text"><font style="color:red;">*</font>暱稱:</div>
				<input type="text" name="nickname" value="<?php echo $user->nickname?>" class="textfield" required><br>
				<div class="blue_text"><font style="color:red;">*</font>姓名:</div>
				<input type="text" name="firstname" value="<?php echo $user->firstname?>" placeholder="名" required><br>
				<input type="text" name="lastname" value="<?php echo $user->lastname?>" placeholder="姓" required><br>
				<div class="blue_text">性別:</div>
				<input type="radio" name="sex" value="m" <?php if($user->sex == 'm') echo 'checked';?>>男
				<input type="radio" name="sex" value="f" <?php if($user->sex == 'f') echo 'checked';?>>女<br>
				<div class="blue_text">生日:</div>
				<input type="date" name="birthday" value="<?php echo $user->birthday?>" class="textfield" ><br>
				<div class="blue_text">電話:</div>
				<input type="tel" name="phone" value="<?php echo $user->phone?>" class="textfield" ><br>
				<div class="blue_text">地址:</div>
				<input type="text" name="address" value="<?php echo $user->address?>" class="textfield"  placeholder="地址"><br>
				<input type="text" name="city" value="<?php echo $user->city?>" placeholder="城市"><br>
				<input type="text" name="district" value="<?php echo $user->district?>" placeholder="鄉鎮市區"><br>
				<input type="text" name="postal" value="<?php echo $user->postal?>" placeholder="郵遞區號"><br>
				<input type="text" name="country" value="<?php echo $user->country?>" placeholder="國家" class="textfield" ><br>
				<input type="submit" class="orange_button" value="儲存" style="margin-top:45px;">
			</form>
		</div>
		
		<script type='text/javascript' src='/js/user_update.js'></script>
	</body>
</html>