<link rel="stylesheet" type="text/css" href="/css/guestbook_create.css">
<script type='text/javascript' src='/js/jquery-1.11.3.min.js'></script>
<script type='text/javascript' src='/js/jquery.form.js'></script>
<script type='text/javascript' src='/js/jquery.validate.js'></script>
<script type='text/javascript' src='/js/jquery.blockUI.js'></script>
<script type='text/javascript' src='/js/guestbook_create.js'></script>
<div id='device_img_wrapper'>
	<?php 
	if(empty($device->photo)) {
		if(!empty($device->type)) {
			switch($device->type) {
				case "Pets":
					echo '<img src="/img/17/pic-01.png">';
					break;
				case "Human":
					echo '<img src="/img/17/pic-02.png">';
					break;
				case "Valuables":
					echo '<img src="/img/17/pic-03.png">';
				default:
					break;
			}
		}
	}
	else {
		echo "<img src='/{$device->photo}'>";
	}
	?>
	<h3><?php echo $device->name?> </h3>
</div>
<div id='title'><img src='/img/08/bu-01.png'/>通知/留言</div>

<div id="guestbook_form_container">
	
	<div class="black_text">
		若你有發現遺失竉物、人或物品的相關資料，請留下您的聯絡方式，幫助遺失的主人順利找回，謝謝～
	</div>
	
	<form action="/guestbook/create" method="post">
		<input type='hidden' name='did' value='<?php echo $device->did;?>'/>
		<input type='hidden' name='serial_number' value='<?php echo $device->serial_number;?>'/>
	    <div class='input_div'>
	        <div class="blue_text"><span><font color="red">*</font>姓名/名稱</span></div>
	        <input id="name" type="text" name="name" class="textfield" required/>
	    </div>		    
	    <div class='input_div'>
	        <div class="blue_text"><span>發現日期</span></div>
	        <input type="date" name="date" class="textfield" />
	    </div>
	    <div class='input_div'>
	        <div class="blue_text"><span>發現時間</span></div>
	        <input type="time" name="time" class="textfield" />
	    </div>
	    <div class='input_div'>
	        <div class="blue_text"><span>發現地點</span></div>
	        <input type="text" name="location" class="textfield" placeholder="請填寫地點或明顯的景點建築"/>
	    </div>
	    <div class='input_div'>
	        <div class="blue_text"><span>聯絡電話</span></div>
	        <input type="tel" name="phone" class="textfield" />
	    </div>
	    <div class='input_div'>
	        <div class="blue_text"><span><font color="red">*</font>留言</span></div>
	        <!-- when print textarea, echo nl2br($message); -->
	        <textarea id="message" name="message" class="textfield" rows=5 placeholder="關於竉物的大小事..." required></textarea>
	    </div>     
	    <div id='submit_div'>
			<button class="button orange_btn" style="" onclick='history.go(-1)'>取 消</button>
			<button type="submit" class="button" style="">送 出</button>
		</div>
		<div class="clear"></div>    
	</form>
</div>
