<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<link rel="stylesheet" type="text/css" href="/css/guestbook_index.css?rand=<?php echo rand(); 	?>">
<?php if(!isset($_SESSION) || !empty($_SESSION)) { ?>
<div id='device_img_wrapper'>
	<?php 
	if(empty($device->photo)) {
		if(!empty($device->type)) {
			switch($device->type) {
				case "Pets":
					echo '<img src="/img/17/pic-02.png">';
					break;
				case "Human":
					echo '<img src="/img/17/pic-01.png">';
					break;
				case "Valuables":
					echo '<img src="/img/17/pic-03.png">';
				default:
					break;
			}
		}
	}
	else {
		echo "<img src='{$device->photo}'>";
	}
	?>
	<h3><?php echo $device->name?> </h3>
</div>
<div id='title'><img src='/img/04/icon-01(white).png'/>通知/留言</div>
<?php } else { ?>
<ul id='title2'>
	<li><a href='/'>首頁</a></li>
	<li> > </li>
	<li><a href='/user'>管理名單</a></li>
	<li> > </li>
	<li><a href='/device/update?serial_number=<?php echo $device->serial_number?>'><?php echo $device->name?></a></li>
	<li> > </li>
	<li style='color:#86c557;'>通知</li>
</ul>	

<?php } ?>

<div id='guestbook_list'>
<?php 
		if($guestbook_list->count() > 0) {

			foreach($guestbook_list as $r) {
				$created = date('Y-m-d',strtotime($r->datetime));
				$phone_link = "";
				
				if(!empty($r->phone))
					$phone_link = "<a class='phone' href='tel:{$r->phone}'><img src='/img/15/phone.png'</a>";
				
				echo <<<EOT
<div class='guestbook'>
	<div class='title'><img class='icon' src='/img/15/1.png'/>{$r->name}</div>
	<div class='date'>{$created}</div>				
	<div class='message1'></div>
	<div class='message2'>{$r->message}</div>	
	<div class='message3'></div>
	<div class='date2'>{$created}</div>		
EOT;
				if(!empty($r->latitude) && !empty($r->longitude) && (date('Y-m-d') <= $device->expiry_date)) {
					echo <<<EOT
	<div class='menu'>{$phone_link} <a class='map' href='http://maps.google.com/?ll={$r->latitude},{$r->longitude}'><img src='/img/map.png'/></a></div>
</div>		
EOT;
				}
			}
		}
		else {
			echo <<<EOT
<p class='grey_text;' style='text-align:center;font-size:4em;color:#808080'>目 前 沒 有 留 言</p>
EOT;
		}
		?>
		<?php if(isset($_SESSION) && !empty($_SESSION)) { ?>
		<a href="/device/update?sn=<?php echo $device->serial_number?>"><div id='home'>回上一頁</div></a>
		<?php } ?>
</div>
