<link rel="stylesheet" type="text/css" href="/css/guestbook_index.css">
<div id='device_img_wrapper'>
	<img src="" style="width:100%;">
	<h3><?php echo $device->name?> </h3>
</div>
<div id='title'><img src='/img/08/bu-01.png'/>通知/留言</div>

<div id='guestbook_list'>
<?php 
		if(!empty($guestbook_list)) {
			foreach($guestbook_list as $r) {
				$created = date('Y-m-d',strtotime($r->datetime));
				echo <<<EOT
<div class='guestbook'>
	<div class='title'><img class='icon' src='/img/15/1.png'/>{$r->name}</div>
	<div class='date'>{$created}</div>				
	<div class='message1'></div>
	<div class='message2'>{$r->message}</div>	
	<div class='message3'></div>
	<div class='date2'>{$created}</div>		
</div>		
EOT;
			}
		}
		?>
		<div id='home'>回首頁</div>
</div>

