<!DOCTYPE html>
<html>
	<head>
		<title>Baby Search - List Guestbook</title>
		<link rel="stylesheet" type="text/css" href="/css/index.css">
	</head>

	<body>
		
		<div class="header">
			<img src="/img/02/logo(white).png" style="margin-top:27.5px;margin-left:2.5%;"></img>
		</div>
		<div>
			<img src="" style="width:100%;height:100%;"><!-- <?php echo $device->name?> --></img>
		</div>
		<div>
			<div style="width:100px;height:100px;float:left;">
				<img src="" style="width:100%;height:100%;"></img>
			</div>
			<div style="height:100px;line-height:100px;font-size:50px;float:left;">通知/留言
			</div>
			<div class="clear"></div>
		</div>
		<a href="/device"><div class="orange_button">回首頁</div></a>
	</body>
</html>